//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_LegacyCmdSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_LegacyCmdSpec")
#ifdef RESTRICT_$AutoValue_LegacyCmdSpec
#define INCLUDE_ALL_$AutoValue_LegacyCmdSpec 0
#else
#define INCLUDE_ALL_$AutoValue_LegacyCmdSpec 1
#endif
#undef RESTRICT_$AutoValue_LegacyCmdSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PI_AutoValue_LegacyCmdSpec_) && (INCLUDE_ALL_$AutoValue_LegacyCmdSpec || defined(INCLUDE_PI_AutoValue_LegacyCmdSpec))
#define PI_AutoValue_LegacyCmdSpec_

#define RESTRICT_LegacyCmdSpec 1
#define INCLUDE_PILegacyCmdSpec 1
#include "LegacyCmdSpec.h"

@class JavaUtilArrayList;
@class PIPushTargetConfigSpec;

@interface PI_AutoValue_LegacyCmdSpec : PILegacyCmdSpec

#pragma mark Public

- (jint)aggressive_a50_state;

- (jint)ax_mode;

- (NSString *)cdn_play_url;

- (jboolean)isEqual:(id)o;

- (jboolean)force_start;

- (NSUInteger)hash;

- (jint)leave_origin_behavior;

- (jboolean)loopback;

- (NSString *)play_br_name;

- (jint)play_mode;

- (jint)play_stream_mode;

- (JavaUtilArrayList *)play_targets;

- (NSString *)play_ve_name;

- (jint)prefer_a50_state;

- (jint)prefer_ax_mode;

- (PIPushTargetConfigSpec *)push_config;

- (jint)push_mode;

- (JavaUtilArrayList *)push_targets;

- (NSString *)push_url_turnp;

- (jint)reason;

- (jint)room_size;

- (jint)scene_play_type;

- (jint)self_ve_a50_state;

- (jint)self_ve_ax_mode;

- (jint)targets_filter_mode;

- (NSString *)description;

- (NSString *)trans_seg_domain;

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)room_size
                    withInt:(jint)reason
                    withInt:(jint)push_mode
      withJavaUtilArrayList:(JavaUtilArrayList *)push_targets
 withPIPushTargetConfigSpec:(PIPushTargetConfigSpec *)push_config
                    withInt:(jint)play_mode
      withJavaUtilArrayList:(JavaUtilArrayList *)play_targets
                withBoolean:(jboolean)force_start
                    withInt:(jint)play_stream_mode
               withNSString:(NSString *)trans_seg_domain
               withNSString:(NSString *)push_url_turnp
               withNSString:(NSString *)cdn_play_url
                    withInt:(jint)leave_origin_behavior
                    withInt:(jint)targets_filter_mode
                    withInt:(jint)scene_play_type
                    withInt:(jint)ax_mode
                    withInt:(jint)self_ve_ax_mode
                    withInt:(jint)prefer_ax_mode
                    withInt:(jint)aggressive_a50_state
                    withInt:(jint)self_ve_a50_state
                    withInt:(jint)prefer_a50_state
               withNSString:(NSString *)play_ve_name
               withNSString:(NSString *)play_br_name
                withBoolean:(jboolean)loopback;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_LegacyCmdSpec)

FOUNDATION_EXPORT void PI_AutoValue_LegacyCmdSpec_initWithInt_withInt_withInt_withJavaUtilArrayList_withPIPushTargetConfigSpec_withInt_withJavaUtilArrayList_withBoolean_withInt_withNSString_withNSString_withNSString_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withNSString_withNSString_withBoolean_(PI_AutoValue_LegacyCmdSpec *self, jint room_size, jint reason, jint push_mode, JavaUtilArrayList *push_targets, PIPushTargetConfigSpec *push_config, jint play_mode, JavaUtilArrayList *play_targets, jboolean force_start, jint play_stream_mode, NSString *trans_seg_domain, NSString *push_url_turnp, NSString *cdn_play_url, jint leave_origin_behavior, jint targets_filter_mode, jint scene_play_type, jint ax_mode, jint self_ve_ax_mode, jint prefer_ax_mode, jint aggressive_a50_state, jint self_ve_a50_state, jint prefer_a50_state, NSString *play_ve_name, NSString *play_br_name, jboolean loopback);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_LegacyCmdSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_LegacyCmdSpec PI_AutoValue_LegacyCmdSpec;

#endif

#if !defined (PI_AutoValue_LegacyCmdSpec_Builder_) && (INCLUDE_ALL_$AutoValue_LegacyCmdSpec || defined(INCLUDE_PI_AutoValue_LegacyCmdSpec_Builder))
#define PI_AutoValue_LegacyCmdSpec_Builder_

#define RESTRICT_LegacyCmdSpec 1
#define INCLUDE_PILegacyCmdSpec_Builder 1
#include "LegacyCmdSpec.h"

@class JavaUtilArrayList;
@class PILegacyCmdSpec;
@class PIPushTargetConfigSpec;

@interface PI_AutoValue_LegacyCmdSpec_Builder : PILegacyCmdSpec_Builder

#pragma mark Public

- (PILegacyCmdSpec_Builder *)aggressive_a50_stateWithInt:(jint)aggressive_a50_state;

- (PILegacyCmdSpec_Builder *)ax_mode:(jint)ax_mode;

- (PILegacyCmdSpec_Builder *)cdn_play_url:(NSString *)cdn_play_url;

- (PILegacyCmdSpec_Builder *)force_start:(jboolean)force_start;

- (PILegacyCmdSpec_Builder *)leave_origin_behavior:(jint)leave_origin_behavior;

- (PILegacyCmdSpec_Builder *)loopback:(jboolean)loopback;

- (PILegacyCmdSpec_Builder *)play_br_name:(NSString *)play_br_name;

- (PILegacyCmdSpec_Builder *)play_mode:(jint)play_mode;

- (PILegacyCmdSpec_Builder *)play_stream_mode:(jint)play_stream_mode;

- (PILegacyCmdSpec_Builder *)play_targets:(JavaUtilArrayList *)play_targets;

- (PILegacyCmdSpec_Builder *)play_ve_name:(NSString *)play_ve_name;

- (PILegacyCmdSpec_Builder *)prefer_a50_stateWithInt:(jint)prefer_a50_state;

- (PILegacyCmdSpec_Builder *)prefer_ax_mode:(jint)prefer_ax_mode;

- (PILegacyCmdSpec_Builder *)push_config:(PIPushTargetConfigSpec *)push_config;

- (PILegacyCmdSpec_Builder *)push_mode:(jint)push_mode;

- (PILegacyCmdSpec_Builder *)push_targets:(JavaUtilArrayList *)push_targets;

- (PILegacyCmdSpec_Builder *)push_url_turnp:(NSString *)push_url_turnp;

- (PILegacyCmdSpec_Builder *)reason:(jint)reason;

- (PILegacyCmdSpec_Builder *)room_size:(jint)room_size;

- (PILegacyCmdSpec_Builder *)scene_play_type:(jint)scene_play_type;

- (PILegacyCmdSpec_Builder *)self_ve_a50_stateWithInt:(jint)self_ve_a50_state;

- (PILegacyCmdSpec_Builder *)self_ve_ax_mode:(jint)self_ve_ax_mode;

- (PILegacyCmdSpec_Builder *)targets_filter_mode:(jint)targets_filter_mode;

- (PILegacyCmdSpec_Builder *)trans_seg_domain:(NSString *)trans_seg_domain;

#pragma mark Package-Private

- (instancetype)init;

- (PILegacyCmdSpec *)autoBuild;

- (jint)ax_mode;

- (jint)prefer_ax_mode;

- (jint)self_ve_ax_mode;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_LegacyCmdSpec_Builder)

FOUNDATION_EXPORT void PI_AutoValue_LegacyCmdSpec_Builder_init(PI_AutoValue_LegacyCmdSpec_Builder *self);

FOUNDATION_EXPORT PI_AutoValue_LegacyCmdSpec_Builder *new_PI_AutoValue_LegacyCmdSpec_Builder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PI_AutoValue_LegacyCmdSpec_Builder *create_PI_AutoValue_LegacyCmdSpec_Builder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_LegacyCmdSpec_Builder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_$AutoValue_LegacyCmdSpec")
