//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_PlayTargetSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_PlayTargetSpec")
#ifdef RESTRICT_$AutoValue_PlayTargetSpec
#define INCLUDE_ALL_$AutoValue_PlayTargetSpec 0
#else
#define INCLUDE_ALL_$AutoValue_PlayTargetSpec 1
#endif
#undef RESTRICT_$AutoValue_PlayTargetSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PI_AutoValue_PlayTargetSpec_) && (INCLUDE_ALL_$AutoValue_PlayTargetSpec || defined(INCLUDE_PI_AutoValue_PlayTargetSpec))
#define PI_AutoValue_PlayTargetSpec_

#define RESTRICT_PlayTargetSpec 1
#define INCLUDE_PIPlayTargetSpec 1
#include "PlayTargetSpec.h"

@class JavaLangInteger;
@class JavaLangLong;
@class PIPlayTargetSpec_Builder;
@protocol JavaUtilList;

@interface PI_AutoValue_PlayTargetSpec : PIPlayTargetSpec

#pragma mark Public

- (NSString *)br_name;

- (jint)diffnum;

- (NSString *)enc_pzb_data;

- (NSString *)enc_url;

- (jboolean)isEqual:(id)o;

- (jboolean)force_start;

- (NSString *)from_uid;

- (NSUInteger)hash;

- (NSString *)key;

- (NSString *)link_extra_params;

- (NSString *)link_pzb_data;

- (NSString *)link_url;

- (jint)mode;

- (jint)play_stream_mode;

- (jint)push_tcs_mode;

- (id<JavaUtilList>)pzb_data;

- (jint)render_mode;

- (NSString *)render_mode_param;

- (jlong)rid;

- (jint)sid;

- (jint)slot;

- (NSString *)srid;

- (JavaLangLong *)stream_group;

- (NSString *)to_uid;

- (PIPlayTargetSpec_Builder *)toBuilder;

- (NSString *)description;

- (id<JavaUtilList>)url;

- (NSString *)ve_name;

- (JavaLangInteger *)ve_slot;

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)key
                        withLong:(jlong)rid
                    withNSString:(NSString *)srid
                withJavaLangLong:(JavaLangLong *)stream_group
             withJavaLangInteger:(JavaLangInteger *)ve_slot
                    withNSString:(NSString *)from_uid
                    withNSString:(NSString *)to_uid
                         withInt:(jint)slot
                         withInt:(jint)diffnum
                         withInt:(jint)sid
                         withInt:(jint)mode
                         withInt:(jint)push_tcs_mode
                withJavaUtilList:(id<JavaUtilList>)url
                withJavaUtilList:(id<JavaUtilList>)pzb_data
                    withNSString:(NSString *)link_extra_params
                     withBoolean:(jboolean)force_start
                         withInt:(jint)play_stream_mode
                    withNSString:(NSString *)ve_name
                    withNSString:(NSString *)br_name
                         withInt:(jint)render_mode
                    withNSString:(NSString *)render_mode_param
                    withNSString:(NSString *)enc_pzb_data
                    withNSString:(NSString *)enc_url
                    withNSString:(NSString *)link_pzb_data
                    withNSString:(NSString *)link_url;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_PlayTargetSpec)

FOUNDATION_EXPORT void PI_AutoValue_PlayTargetSpec_initWithNSString_withLong_withNSString_withJavaLangLong_withJavaLangInteger_withNSString_withNSString_withInt_withInt_withInt_withInt_withInt_withJavaUtilList_withJavaUtilList_withNSString_withBoolean_withInt_withNSString_withNSString_withInt_withNSString_withNSString_withNSString_withNSString_withNSString_(PI_AutoValue_PlayTargetSpec *self, NSString *key, jlong rid, NSString *srid, JavaLangLong *stream_group, JavaLangInteger *ve_slot, NSString *from_uid, NSString *to_uid, jint slot, jint diffnum, jint sid, jint mode, jint push_tcs_mode, id<JavaUtilList> url, id<JavaUtilList> pzb_data, NSString *link_extra_params, jboolean force_start, jint play_stream_mode, NSString *ve_name, NSString *br_name, jint render_mode, NSString *render_mode_param, NSString *enc_pzb_data, NSString *enc_url, NSString *link_pzb_data, NSString *link_url);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_PlayTargetSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_PlayTargetSpec PI_AutoValue_PlayTargetSpec;

#endif

#if !defined (PI_AutoValue_PlayTargetSpec_Builder_) && (INCLUDE_ALL_$AutoValue_PlayTargetSpec || defined(INCLUDE_PI_AutoValue_PlayTargetSpec_Builder))
#define PI_AutoValue_PlayTargetSpec_Builder_

#define RESTRICT_PlayTargetSpec 1
#define INCLUDE_PIPlayTargetSpec_Builder 1
#include "PlayTargetSpec.h"

@class JavaLangInteger;
@class JavaLangLong;
@class PIPlayTargetSpec;
@protocol JavaUtilList;

@interface PI_AutoValue_PlayTargetSpec_Builder : PIPlayTargetSpec_Builder

#pragma mark Public

- (PIPlayTargetSpec_Builder *)br_name:(NSString *)br_name;

- (PIPlayTargetSpec *)build;

- (PIPlayTargetSpec_Builder *)diffnum:(jint)diffnum;

- (PIPlayTargetSpec_Builder *)enc_pzb_dataWithNSString:(NSString *)enc_pzb_data;

- (PIPlayTargetSpec_Builder *)enc_urlWithNSString:(NSString *)enc_url;

- (PIPlayTargetSpec_Builder *)force_start:(jboolean)force_start;

- (PIPlayTargetSpec_Builder *)from_uid:(NSString *)from_uid;

- (PIPlayTargetSpec_Builder *)key:(NSString *)key;

- (PIPlayTargetSpec_Builder *)link_extra_params:(NSString *)link_extra_params;

- (PIPlayTargetSpec_Builder *)link_pzb_dataWithNSString:(NSString *)link_pzb_data;

- (PIPlayTargetSpec_Builder *)link_urlWithNSString:(NSString *)link_url;

- (PIPlayTargetSpec_Builder *)mode:(jint)mode;

- (PIPlayTargetSpec_Builder *)play_stream_mode:(jint)play_stream_mode;

- (PIPlayTargetSpec_Builder *)push_tcs_mode:(jint)push_tcs_mode;

- (PIPlayTargetSpec_Builder *)pzb_data:(id<JavaUtilList>)pzb_data;

- (PIPlayTargetSpec_Builder *)render_mode:(jint)render_mode;

- (PIPlayTargetSpec_Builder *)render_mode_param:(NSString *)render_mode_param;

- (PIPlayTargetSpec_Builder *)ridWithLong:(jlong)rid;

- (PIPlayTargetSpec_Builder *)sid:(jint)sid;

- (PIPlayTargetSpec_Builder *)slot:(jint)slot;

- (PIPlayTargetSpec_Builder *)srid:(NSString *)srid;

- (PIPlayTargetSpec_Builder *)stream_group:(JavaLangLong *)stream_group;

- (PIPlayTargetSpec_Builder *)to_uid:(NSString *)to_uid;

- (PIPlayTargetSpec_Builder *)url:(id<JavaUtilList>)url;

- (PIPlayTargetSpec_Builder *)ve_name:(NSString *)ve_name;

- (PIPlayTargetSpec_Builder *)ve_slot:(JavaLangInteger *)ve_slot;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_PlayTargetSpec_Builder)

FOUNDATION_EXPORT void PI_AutoValue_PlayTargetSpec_Builder_init(PI_AutoValue_PlayTargetSpec_Builder *self);

FOUNDATION_EXPORT PI_AutoValue_PlayTargetSpec_Builder *new_PI_AutoValue_PlayTargetSpec_Builder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PI_AutoValue_PlayTargetSpec_Builder *create_PI_AutoValue_PlayTargetSpec_Builder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_PlayTargetSpec_Builder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_$AutoValue_PlayTargetSpec")
