//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_CmdSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_CmdSpec")
#ifdef RESTRICT_$AutoValue_CmdSpec
#define INCLUDE_ALL_$AutoValue_CmdSpec 0
#else
#define INCLUDE_ALL_$AutoValue_CmdSpec 1
#endif
#undef RESTRICT_$AutoValue_CmdSpec

#if !defined (PI_AutoValue_CmdSpec_) && (INCLUDE_ALL_$AutoValue_CmdSpec || defined(INCLUDE_PI_AutoValue_CmdSpec))
#define PI_AutoValue_CmdSpec_

#define RESTRICT_CmdSpec 1
#define INCLUDE_PICmdSpec 1
#include "CmdSpec.h"

@interface PI_AutoValue_CmdSpec : PICmdSpec

#pragma mark Public

- (NSString *)cmd;

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

- (jlong)rid;

- (NSString *)srid;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithLong:(jlong)rid
                withNSString:(NSString *)srid
                withNSString:(NSString *)cmd;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_CmdSpec)

FOUNDATION_EXPORT void PI_AutoValue_CmdSpec_initWithLong_withNSString_withNSString_(PI_AutoValue_CmdSpec *self, jlong rid, NSString *srid, NSString *cmd);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_CmdSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_CmdSpec PI_AutoValue_CmdSpec;

#endif

#pragma pop_macro("INCLUDE_ALL_$AutoValue_CmdSpec")
