//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_PushTargetConfigSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_PushTargetConfigSpec")
#ifdef RESTRICT_$AutoValue_PushTargetConfigSpec
#define INCLUDE_ALL_$AutoValue_PushTargetConfigSpec 0
#else
#define INCLUDE_ALL_$AutoValue_PushTargetConfigSpec 1
#endif
#undef RESTRICT_$AutoValue_PushTargetConfigSpec

#if !defined (PI_AutoValue_PushTargetConfigSpec_) && (INCLUDE_ALL_$AutoValue_PushTargetConfigSpec || defined(INCLUDE_PI_AutoValue_PushTargetConfigSpec))
#define PI_AutoValue_PushTargetConfigSpec_

#define RESTRICT_PushTargetConfigSpec 1
#define INCLUDE_PIPushTargetConfigSpec 1
#include "PushTargetConfigSpec.h"

@class PIPushTargetConfigSpec_Builder;

@interface PI_AutoValue_PushTargetConfigSpec : PIPushTargetConfigSpec

#pragma mark Public

- (jint)bitrate;

- (jboolean)isEqual:(id)o;

- (jint)fps;

- (NSUInteger)hash;

- (jint)height;

- (jint)max_br;

- (jint)min_br;

- (jint)min_fps;

- (jint)preview_height;

- (jint)preview_width;

- (jint)tcs_mode;

- (PIPushTargetConfigSpec_Builder *)toBuilder;

- (NSString *)description;

- (jint)video_codec;

- (jint)width;

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)tcs_mode
                    withInt:(jint)preview_width
                    withInt:(jint)preview_height
                    withInt:(jint)fps
                    withInt:(jint)min_fps
                    withInt:(jint)width
                    withInt:(jint)height
                    withInt:(jint)bitrate
                    withInt:(jint)max_br
                    withInt:(jint)min_br
                    withInt:(jint)video_codec;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_PushTargetConfigSpec)

FOUNDATION_EXPORT void PI_AutoValue_PushTargetConfigSpec_initWithInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_(PI_AutoValue_PushTargetConfigSpec *self, jint tcs_mode, jint preview_width, jint preview_height, jint fps, jint min_fps, jint width, jint height, jint bitrate, jint max_br, jint min_br, jint video_codec);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_PushTargetConfigSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_PushTargetConfigSpec PI_AutoValue_PushTargetConfigSpec;

#endif

#if !defined (PI_AutoValue_PushTargetConfigSpec_Builder_) && (INCLUDE_ALL_$AutoValue_PushTargetConfigSpec || defined(INCLUDE_PI_AutoValue_PushTargetConfigSpec_Builder))
#define PI_AutoValue_PushTargetConfigSpec_Builder_

#define RESTRICT_PushTargetConfigSpec 1
#define INCLUDE_PIPushTargetConfigSpec_Builder 1
#include "PushTargetConfigSpec.h"

@class PIPushTargetConfigSpec;

@interface PI_AutoValue_PushTargetConfigSpec_Builder : PIPushTargetConfigSpec_Builder

#pragma mark Public

- (PIPushTargetConfigSpec_Builder *)bitrate:(jint)bitrate;

- (PIPushTargetConfigSpec *)build;

- (PIPushTargetConfigSpec_Builder *)fps:(jint)fps;

- (PIPushTargetConfigSpec_Builder *)height:(jint)height;

- (PIPushTargetConfigSpec_Builder *)max_br:(jint)max_br;

- (PIPushTargetConfigSpec_Builder *)min_br:(jint)min_br;

- (PIPushTargetConfigSpec_Builder *)min_fps:(jint)min_fps;

- (PIPushTargetConfigSpec_Builder *)preview_height:(jint)preview_height;

- (PIPushTargetConfigSpec_Builder *)preview_width:(jint)preview_width;

- (PIPushTargetConfigSpec_Builder *)tcs_mode:(jint)tcs_mode;

- (PIPushTargetConfigSpec_Builder *)video_codec:(jint)video_codec;

- (PIPushTargetConfigSpec_Builder *)width:(jint)width;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_PushTargetConfigSpec_Builder)

FOUNDATION_EXPORT void PI_AutoValue_PushTargetConfigSpec_Builder_init(PI_AutoValue_PushTargetConfigSpec_Builder *self);

FOUNDATION_EXPORT PI_AutoValue_PushTargetConfigSpec_Builder *new_PI_AutoValue_PushTargetConfigSpec_Builder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PI_AutoValue_PushTargetConfigSpec_Builder *create_PI_AutoValue_PushTargetConfigSpec_Builder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_PushTargetConfigSpec_Builder)

#endif

#pragma pop_macro("INCLUDE_ALL_$AutoValue_PushTargetConfigSpec")
