//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_MetronomeChannelConfigSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_MetronomeChannelConfigSpec")
#ifdef RESTRICT_$AutoValue_MetronomeChannelConfigSpec
#define INCLUDE_ALL_$AutoValue_MetronomeChannelConfigSpec 0
#else
#define INCLUDE_ALL_$AutoValue_MetronomeChannelConfigSpec 1
#endif
#undef RESTRICT_$AutoValue_MetronomeChannelConfigSpec

#if !defined (PI_AutoValue_MetronomeChannelConfigSpec_) && (INCLUDE_ALL_$AutoValue_MetronomeChannelConfigSpec || defined(INCLUDE_PI_AutoValue_MetronomeChannelConfigSpec))
#define PI_AutoValue_MetronomeChannelConfigSpec_

#define RESTRICT_MetronomeChannelConfigSpec 1
#define INCLUDE_PIMetronomeChannelConfigSpec 1
#include "MetronomeChannelConfigSpec.h"

@protocol JavaUtilList;

@interface PI_AutoValue_MetronomeChannelConfigSpec : PIMetronomeChannelConfigSpec

#pragma mark Public

- (id<JavaUtilList>)beats;

- (jint)beats_count;

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

- (jint)note;

- (jlong)pzvt;

- (jint)rate;

- (id<JavaUtilList>)source;

- (jint)ssrc;

- (jboolean)streaming;

- (jboolean)sync_fix;

- (NSString *)description;

- (jint)volume;

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)ssrc
                   withLong:(jlong)pzvt
                    withInt:(jint)note
                    withInt:(jint)rate
                    withInt:(jint)beats_count
                    withInt:(jint)volume
                withBoolean:(jboolean)streaming
                withBoolean:(jboolean)sync_fix
           withJavaUtilList:(id<JavaUtilList>)source
           withJavaUtilList:(id<JavaUtilList>)beats;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_MetronomeChannelConfigSpec)

FOUNDATION_EXPORT void PI_AutoValue_MetronomeChannelConfigSpec_initWithInt_withLong_withInt_withInt_withInt_withInt_withBoolean_withBoolean_withJavaUtilList_withJavaUtilList_(PI_AutoValue_MetronomeChannelConfigSpec *self, jint ssrc, jlong pzvt, jint note, jint rate, jint beats_count, jint volume, jboolean streaming, jboolean sync_fix, id<JavaUtilList> source, id<JavaUtilList> beats);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_MetronomeChannelConfigSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_MetronomeChannelConfigSpec PI_AutoValue_MetronomeChannelConfigSpec;

#endif

#pragma pop_macro("INCLUDE_ALL_$AutoValue_MetronomeChannelConfigSpec")
