//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_PlayerStatusInfo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_PlayerStatusInfo")
#ifdef RESTRICT_$AutoValue_PlayerStatusInfo
#define INCLUDE_ALL_$AutoValue_PlayerStatusInfo 0
#else
#define INCLUDE_ALL_$AutoValue_PlayerStatusInfo 1
#endif
#undef RESTRICT_$AutoValue_PlayerStatusInfo

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PI_AutoValue_PlayerStatusInfo_) && (INCLUDE_ALL_$AutoValue_PlayerStatusInfo || defined(INCLUDE_PI_AutoValue_PlayerStatusInfo))
#define PI_AutoValue_PlayerStatusInfo_

#define RESTRICT_PlayerStatusInfo 1
#define INCLUDE_PIPlayerStatusInfo 1
#include "PlayerStatusInfo.h"

@interface PI_AutoValue_PlayerStatusInfo : PIPlayerStatusInfo

#pragma mark Public

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

- (jint)pzvt_delay;

- (NSString *)description;

- (NSString *)uid;

- (NSString *)ve_name;

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)uid
                    withNSString:(NSString *)ve_name
                         withInt:(jint)pzvt_delay;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_PlayerStatusInfo)

FOUNDATION_EXPORT void PI_AutoValue_PlayerStatusInfo_initWithNSString_withNSString_withInt_(PI_AutoValue_PlayerStatusInfo *self, NSString *uid, NSString *ve_name, jint pzvt_delay);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_PlayerStatusInfo)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_PlayerStatusInfo PI_AutoValue_PlayerStatusInfo;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_$AutoValue_PlayerStatusInfo")
