//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_MergeInfoSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_MergeInfoSpec")
#ifdef RESTRICT_$AutoValue_MergeInfoSpec
#define INCLUDE_ALL_$AutoValue_MergeInfoSpec 0
#else
#define INCLUDE_ALL_$AutoValue_MergeInfoSpec 1
#endif
#undef RESTRICT_$AutoValue_MergeInfoSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PI_AutoValue_MergeInfoSpec_) && (INCLUDE_ALL_$AutoValue_MergeInfoSpec || defined(INCLUDE_PI_AutoValue_MergeInfoSpec))
#define PI_AutoValue_MergeInfoSpec_

#define RESTRICT_MergeInfoSpec 1
#define INCLUDE_PIMergeInfoSpec 1
#include "MergeInfoSpec.h"

@class JavaUtilArrayList;

@interface PI_AutoValue_MergeInfoSpec : PIMergeInfoSpec

#pragma mark Public

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

- (NSString *)primary_sroom;

- (JavaUtilArrayList *)srooms;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)primary_sroom
           withJavaUtilArrayList:(JavaUtilArrayList *)srooms;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_MergeInfoSpec)

FOUNDATION_EXPORT void PI_AutoValue_MergeInfoSpec_initWithNSString_withJavaUtilArrayList_(PI_AutoValue_MergeInfoSpec *self, NSString *primary_sroom, JavaUtilArrayList *srooms);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_MergeInfoSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_MergeInfoSpec PI_AutoValue_MergeInfoSpec;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_$AutoValue_MergeInfoSpec")
