//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_RxConfigSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_RxConfigSpec")
#ifdef RESTRICT_$AutoValue_RxConfigSpec
#define INCLUDE_ALL_$AutoValue_RxConfigSpec 0
#else
#define INCLUDE_ALL_$AutoValue_RxConfigSpec 1
#endif
#undef RESTRICT_$AutoValue_RxConfigSpec

#if !defined (PI_AutoValue_RxConfigSpec_) && (INCLUDE_ALL_$AutoValue_RxConfigSpec || defined(INCLUDE_PI_AutoValue_RxConfigSpec))
#define PI_AutoValue_RxConfigSpec_

#define RESTRICT_RxConfigSpec 1
#define INCLUDE_PIRxConfigSpec 1
#include "RxConfigSpec.h"

@interface PI_AutoValue_RxConfigSpec : PIRxConfigSpec

#pragma mark Public

- (jlong)a50_inactive_threshold;

- (jint)a50_refresh_interval;

- (jint)a50_state_check_interval;

- (jboolean)isEqual:(id)o;

- (jint)fs_bc_interval;

- (jint)fs_bc_self_interval;

- (NSUInteger)hash;

- (jint)hb;

- (jint)hb_timeout;

- (jboolean)play_one_auto_ve_change;

- (jint)refresh;

- (jint)rx_retry;

- (jint)rx_timeout;

- (NSString *)description;

- (jint)ve_sync_play_interval;

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)refresh
                    withInt:(jint)hb
                    withInt:(jint)fs_bc_interval
                    withInt:(jint)fs_bc_self_interval
                    withInt:(jint)a50_refresh_interval
                    withInt:(jint)a50_state_check_interval
                    withInt:(jint)ve_sync_play_interval
                    withInt:(jint)hb_timeout
                    withInt:(jint)rx_timeout
                    withInt:(jint)rx_retry
                withBoolean:(jboolean)play_one_auto_ve_change
                   withLong:(jlong)a50_inactive_threshold;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_RxConfigSpec)

FOUNDATION_EXPORT void PI_AutoValue_RxConfigSpec_initWithInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withBoolean_withLong_(PI_AutoValue_RxConfigSpec *self, jint refresh, jint hb, jint fs_bc_interval, jint fs_bc_self_interval, jint a50_refresh_interval, jint a50_state_check_interval, jint ve_sync_play_interval, jint hb_timeout, jint rx_timeout, jint rx_retry, jboolean play_one_auto_ve_change, jlong a50_inactive_threshold);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_RxConfigSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_RxConfigSpec PI_AutoValue_RxConfigSpec;

#endif

#if !defined (PI_AutoValue_RxConfigSpec_Builder_) && (INCLUDE_ALL_$AutoValue_RxConfigSpec || defined(INCLUDE_PI_AutoValue_RxConfigSpec_Builder))
#define PI_AutoValue_RxConfigSpec_Builder_

#define RESTRICT_RxConfigSpec 1
#define INCLUDE_PIRxConfigSpec_Builder 1
#include "RxConfigSpec.h"

@class PIRxConfigSpec;

@interface PI_AutoValue_RxConfigSpec_Builder : PIRxConfigSpec_Builder

#pragma mark Public

- (PIRxConfigSpec_Builder *)a50_inactive_threshold:(jlong)a50_inactive_threshold;

- (PIRxConfigSpec_Builder *)a50_refresh_interval:(jint)a50_refresh_interval;

- (PIRxConfigSpec_Builder *)a50_state_check_interval:(jint)a50_state_check_interval;

- (PIRxConfigSpec *)build;

- (PIRxConfigSpec_Builder *)fs_bc_interval:(jint)fs_bc_interval;

- (PIRxConfigSpec_Builder *)fs_bc_self_interval:(jint)fs_bc_self_interval;

- (PIRxConfigSpec_Builder *)hb:(jint)hb;

- (PIRxConfigSpec_Builder *)hb_timeout:(jint)hb_timeout;

- (PIRxConfigSpec_Builder *)play_one_auto_ve_change:(jboolean)play_one_auto_ve_change;

- (PIRxConfigSpec_Builder *)refresh:(jint)refresh;

- (PIRxConfigSpec_Builder *)rx_retry:(jint)rx_retry;

- (PIRxConfigSpec_Builder *)rx_timeout:(jint)rx_timeout;

- (PIRxConfigSpec_Builder *)ve_sync_play_interval:(jint)ve_sync_play_interval;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_RxConfigSpec_Builder)

FOUNDATION_EXPORT void PI_AutoValue_RxConfigSpec_Builder_init(PI_AutoValue_RxConfigSpec_Builder *self);

FOUNDATION_EXPORT PI_AutoValue_RxConfigSpec_Builder *new_PI_AutoValue_RxConfigSpec_Builder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PI_AutoValue_RxConfigSpec_Builder *create_PI_AutoValue_RxConfigSpec_Builder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_RxConfigSpec_Builder)

#endif

#pragma pop_macro("INCLUDE_ALL_$AutoValue_RxConfigSpec")
