//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/$AutoValue_ChangeRefreshResultSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_$AutoValue_ChangeRefreshResultSpec")
#ifdef RESTRICT_$AutoValue_ChangeRefreshResultSpec
#define INCLUDE_ALL_$AutoValue_ChangeRefreshResultSpec 0
#else
#define INCLUDE_ALL_$AutoValue_ChangeRefreshResultSpec 1
#endif
#undef RESTRICT_$AutoValue_ChangeRefreshResultSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PI_AutoValue_ChangeRefreshResultSpec_) && (INCLUDE_ALL_$AutoValue_ChangeRefreshResultSpec || defined(INCLUDE_PI_AutoValue_ChangeRefreshResultSpec))
#define PI_AutoValue_ChangeRefreshResultSpec_

#define RESTRICT_ChangeRefreshResultSpec 1
#define INCLUDE_PIChangeRefreshResultSpec 1
#include "ChangeRefreshResultSpec.h"

@class PIChangeRefreshResultSpec_Sig;
@class PIRxConfigSpec;
@class PISigCmd;
@protocol JavaUtilList;

@interface PI_AutoValue_ChangeRefreshResultSpec : PIChangeRefreshResultSpec

#pragma mark Public

- (NSString *)app_private_data;

- (jint)enable_ve_opt;

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

- (id<JavaUtilList>)joined_srooms;

- (NSString *)mc_global_params;

- (id<JavaUtilList>)play_targets;

- (id<JavaUtilList>)push_targets;

- (jint)refresh;

- (jint)rs_result;

- (PIRxConfigSpec *)rx_config;

- (jint)scene_play_type;

- (PIChangeRefreshResultSpec_Sig *)sig;

- (PISigCmd *)sigcmd;

- (jint)status_policy;

- (id<JavaUtilList>)stream_event_cmd;

- (NSString *)description;

- (id<JavaUtilList>)us_acts;

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)rs_result
                    withInt:(jint)enable_ve_opt
                    withInt:(jint)scene_play_type
                    withInt:(jint)refresh
               withNSString:(NSString *)app_private_data
                    withInt:(jint)status_policy
           withJavaUtilList:(id<JavaUtilList>)joined_srooms
           withJavaUtilList:(id<JavaUtilList>)push_targets
           withJavaUtilList:(id<JavaUtilList>)play_targets
               withPISigCmd:(PISigCmd *)sigcmd
           withJavaUtilList:(id<JavaUtilList>)stream_event_cmd
           withJavaUtilList:(id<JavaUtilList>)us_acts
         withPIRxConfigSpec:(PIRxConfigSpec *)rx_config
               withNSString:(NSString *)mc_global_params
withPIChangeRefreshResultSpec_Sig:(PIChangeRefreshResultSpec_Sig *)sig;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_ChangeRefreshResultSpec)

FOUNDATION_EXPORT void PI_AutoValue_ChangeRefreshResultSpec_initWithInt_withInt_withInt_withInt_withNSString_withInt_withJavaUtilList_withJavaUtilList_withJavaUtilList_withPISigCmd_withJavaUtilList_withJavaUtilList_withPIRxConfigSpec_withNSString_withPIChangeRefreshResultSpec_Sig_(PI_AutoValue_ChangeRefreshResultSpec *self, jint rs_result, jint enable_ve_opt, jint scene_play_type, jint refresh, NSString *app_private_data, jint status_policy, id<JavaUtilList> joined_srooms, id<JavaUtilList> push_targets, id<JavaUtilList> play_targets, PISigCmd *sigcmd, id<JavaUtilList> stream_event_cmd, id<JavaUtilList> us_acts, PIRxConfigSpec *rx_config, NSString *mc_global_params, PIChangeRefreshResultSpec_Sig *sig);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_ChangeRefreshResultSpec)

@compatibility_alias ComPowerinfoPi_iroomData$AutoValue_ChangeRefreshResultSpec PI_AutoValue_ChangeRefreshResultSpec;

#endif

#if !defined (PI_AutoValue_ChangeRefreshResultSpec_Builder_) && (INCLUDE_ALL_$AutoValue_ChangeRefreshResultSpec || defined(INCLUDE_PI_AutoValue_ChangeRefreshResultSpec_Builder))
#define PI_AutoValue_ChangeRefreshResultSpec_Builder_

#define RESTRICT_ChangeRefreshResultSpec 1
#define INCLUDE_PIChangeRefreshResultSpec_Builder 1
#include "ChangeRefreshResultSpec.h"

@class PIChangeRefreshResultSpec;
@class PIChangeRefreshResultSpec_Sig;
@class PIRxConfigSpec;
@class PISigCmd;
@protocol JavaUtilList;

@interface PI_AutoValue_ChangeRefreshResultSpec_Builder : PIChangeRefreshResultSpec_Builder

#pragma mark Public

- (PIChangeRefreshResultSpec_Builder *)app_private_data:(NSString *)app_private_data;

- (PIChangeRefreshResultSpec *)build;

- (PIChangeRefreshResultSpec_Builder *)enable_ve_opt:(jint)enable_ve_opt;

- (PIChangeRefreshResultSpec_Builder *)joined_srooms:(id<JavaUtilList>)joined_srooms;

- (PIChangeRefreshResultSpec_Builder *)mc_global_params:(NSString *)mc_global_params;

- (PIChangeRefreshResultSpec_Builder *)play_targets:(id<JavaUtilList>)play_targets;

- (PIChangeRefreshResultSpec_Builder *)push_targets:(id<JavaUtilList>)push_targets;

- (PIChangeRefreshResultSpec_Builder *)refresh:(jint)refresh;

- (PIChangeRefreshResultSpec_Builder *)rs_result:(jint)rs_result;

- (PIChangeRefreshResultSpec_Builder *)rx_config:(PIRxConfigSpec *)rx_config;

- (PIChangeRefreshResultSpec_Builder *)scene_play_type:(jint)scene_play_type;

- (PIChangeRefreshResultSpec_Builder *)sig:(PIChangeRefreshResultSpec_Sig *)sig;

- (PIChangeRefreshResultSpec_Builder *)sigcmd:(PISigCmd *)sigcmd;

- (PIChangeRefreshResultSpec_Builder *)status_policy:(jint)status_policy;

- (PIChangeRefreshResultSpec_Builder *)stream_event_cmd:(id<JavaUtilList>)stream_event_cmd;

- (PIChangeRefreshResultSpec_Builder *)us_acts:(id<JavaUtilList>)us_acts;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(PI_AutoValue_ChangeRefreshResultSpec_Builder)

FOUNDATION_EXPORT void PI_AutoValue_ChangeRefreshResultSpec_Builder_init(PI_AutoValue_ChangeRefreshResultSpec_Builder *self);

FOUNDATION_EXPORT PI_AutoValue_ChangeRefreshResultSpec_Builder *new_PI_AutoValue_ChangeRefreshResultSpec_Builder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PI_AutoValue_ChangeRefreshResultSpec_Builder *create_PI_AutoValue_ChangeRefreshResultSpec_Builder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(PI_AutoValue_ChangeRefreshResultSpec_Builder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_$AutoValue_ChangeRefreshResultSpec")
