//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/utils/Action1.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Action1")
#ifdef RESTRICT_Action1
#define INCLUDE_ALL_Action1 0
#else
#define INCLUDE_ALL_Action1 1
#endif
#undef RESTRICT_Action1

#if !defined (PIAction1_) && (INCLUDE_ALL_Action1 || defined(INCLUDE_PIAction1))
#define PIAction1_

@protocol PIAction1 < JavaObject >

- (void)call:(id)param;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAction1)

J2OBJC_TYPE_LITERAL_HEADER(PIAction1)

#define ComPowerinfoPi_iroomUtilsAction1 PIAction1

#endif

#pragma pop_macro("INCLUDE_ALL_Action1")
