//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/utils/Action0.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Action0")
#ifdef RESTRICT_Action0
#define INCLUDE_ALL_Action0 0
#else
#define INCLUDE_ALL_Action0 1
#endif
#undef RESTRICT_Action0

#if !defined (PIAction0_) && (INCLUDE_ALL_Action0 || defined(INCLUDE_PIAction0))
#define PIAction0_

@protocol PIAction0 < JavaObject >

- (void)call;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAction0)

J2OBJC_TYPE_LITERAL_HEADER(PIAction0)

#define ComPowerinfoPi_iroomUtilsAction0 PIAction0

#endif

#pragma pop_macro("INCLUDE_ALL_Action0")
