//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_MetronomeChannelConfigSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_MetronomeChannelConfigSpec")
#ifdef RESTRICT_AutoValue_MetronomeChannelConfigSpec
#define INCLUDE_ALL_AutoValue_MetronomeChannelConfigSpec 0
#else
#define INCLUDE_ALL_AutoValue_MetronomeChannelConfigSpec 1
#endif
#undef RESTRICT_AutoValue_MetronomeChannelConfigSpec

#if !defined (PIAutoValue_MetronomeChannelConfigSpec_) && (INCLUDE_ALL_AutoValue_MetronomeChannelConfigSpec || defined(INCLUDE_PIAutoValue_MetronomeChannelConfigSpec))
#define PIAutoValue_MetronomeChannelConfigSpec_

#define RESTRICT_$AutoValue_MetronomeChannelConfigSpec 1
#define INCLUDE_PI_AutoValue_MetronomeChannelConfigSpec 1
#include "$AutoValue_MetronomeChannelConfigSpec.h"

@protocol JavaUtilList;

@interface PIAutoValue_MetronomeChannelConfigSpec : PI_AutoValue_MetronomeChannelConfigSpec

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)ssrc
                   withLong:(jlong)pzvt
                    withInt:(jint)note
                    withInt:(jint)rate
                    withInt:(jint)beats_count
                    withInt:(jint)volume
                withBoolean:(jboolean)streaming
                withBoolean:(jboolean)sync_fix
           withJavaUtilList:(id<JavaUtilList>)source
           withJavaUtilList:(id<JavaUtilList>)beats;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_MetronomeChannelConfigSpec)

FOUNDATION_EXPORT void PIAutoValue_MetronomeChannelConfigSpec_initWithInt_withLong_withInt_withInt_withInt_withInt_withBoolean_withBoolean_withJavaUtilList_withJavaUtilList_(PIAutoValue_MetronomeChannelConfigSpec *self, jint ssrc, jlong pzvt, jint note, jint rate, jint beats_count, jint volume, jboolean streaming, jboolean sync_fix, id<JavaUtilList> source, id<JavaUtilList> beats);

FOUNDATION_EXPORT PIAutoValue_MetronomeChannelConfigSpec *new_PIAutoValue_MetronomeChannelConfigSpec_initWithInt_withLong_withInt_withInt_withInt_withInt_withBoolean_withBoolean_withJavaUtilList_withJavaUtilList_(jint ssrc, jlong pzvt, jint note, jint rate, jint beats_count, jint volume, jboolean streaming, jboolean sync_fix, id<JavaUtilList> source, id<JavaUtilList> beats) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_MetronomeChannelConfigSpec *create_PIAutoValue_MetronomeChannelConfigSpec_initWithInt_withLong_withInt_withInt_withInt_withInt_withBoolean_withBoolean_withJavaUtilList_withJavaUtilList_(jint ssrc, jlong pzvt, jint note, jint rate, jint beats_count, jint volume, jboolean streaming, jboolean sync_fix, id<JavaUtilList> source, id<JavaUtilList> beats);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_MetronomeChannelConfigSpec)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_MetronomeChannelConfigSpec PIAutoValue_MetronomeChannelConfigSpec;

#endif

#if !defined (PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_MetronomeChannelConfigSpec || defined(INCLUDE_PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter))
#define PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PIMetronomeChannelConfigSpec;

@interface PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PIMetronomeChannelConfigSpec *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PIMetronomeChannelConfigSpec *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PIMetronomeChannelConfigSpec *)fromJsonWithNSString:(NSString *)arg0;

- (PIMetronomeChannelConfigSpec *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PIMetronomeChannelConfigSpec *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter *new_PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter *create_PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_MetronomeChannelConfigSpec_GsonTypeAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_AutoValue_MetronomeChannelConfigSpec")
