//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_SplitInfoSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_SplitInfoSpec")
#ifdef RESTRICT_AutoValue_SplitInfoSpec
#define INCLUDE_ALL_AutoValue_SplitInfoSpec 0
#else
#define INCLUDE_ALL_AutoValue_SplitInfoSpec 1
#endif
#undef RESTRICT_AutoValue_SplitInfoSpec

#if !defined (PIAutoValue_SplitInfoSpec_) && (INCLUDE_ALL_AutoValue_SplitInfoSpec || defined(INCLUDE_PIAutoValue_SplitInfoSpec))
#define PIAutoValue_SplitInfoSpec_

#define RESTRICT_$AutoValue_SplitInfoSpec 1
#define INCLUDE_PI_AutoValue_SplitInfoSpec 1
#include "$AutoValue_SplitInfoSpec.h"

@class JavaUtilArrayList;

@interface PIAutoValue_SplitInfoSpec : PI_AutoValue_SplitInfoSpec

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)old_primary_sroom
           withJavaUtilArrayList:(JavaUtilArrayList *)split;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_SplitInfoSpec)

FOUNDATION_EXPORT void PIAutoValue_SplitInfoSpec_initWithNSString_withJavaUtilArrayList_(PIAutoValue_SplitInfoSpec *self, NSString *old_primary_sroom, JavaUtilArrayList *split);

FOUNDATION_EXPORT PIAutoValue_SplitInfoSpec *new_PIAutoValue_SplitInfoSpec_initWithNSString_withJavaUtilArrayList_(NSString *old_primary_sroom, JavaUtilArrayList *split) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_SplitInfoSpec *create_PIAutoValue_SplitInfoSpec_initWithNSString_withJavaUtilArrayList_(NSString *old_primary_sroom, JavaUtilArrayList *split);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_SplitInfoSpec)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_SplitInfoSpec PIAutoValue_SplitInfoSpec;

#endif

#if !defined (PIAutoValue_SplitInfoSpec_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_SplitInfoSpec || defined(INCLUDE_PIAutoValue_SplitInfoSpec_GsonTypeAdapter))
#define PIAutoValue_SplitInfoSpec_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PISplitInfoSpec;

@interface PIAutoValue_SplitInfoSpec_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PISplitInfoSpec *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PISplitInfoSpec *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PISplitInfoSpec *)fromJsonWithNSString:(NSString *)arg0;

- (PISplitInfoSpec *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PISplitInfoSpec *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_SplitInfoSpec_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_SplitInfoSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_SplitInfoSpec_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_SplitInfoSpec_GsonTypeAdapter *new_PIAutoValue_SplitInfoSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_SplitInfoSpec_GsonTypeAdapter *create_PIAutoValue_SplitInfoSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_SplitInfoSpec_GsonTypeAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_AutoValue_SplitInfoSpec")
