//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_RxConfigSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_RxConfigSpec")
#ifdef RESTRICT_AutoValue_RxConfigSpec
#define INCLUDE_ALL_AutoValue_RxConfigSpec 0
#else
#define INCLUDE_ALL_AutoValue_RxConfigSpec 1
#endif
#undef RESTRICT_AutoValue_RxConfigSpec

#if !defined (PIAutoValue_RxConfigSpec_) && (INCLUDE_ALL_AutoValue_RxConfigSpec || defined(INCLUDE_PIAutoValue_RxConfigSpec))
#define PIAutoValue_RxConfigSpec_

#define RESTRICT_$AutoValue_RxConfigSpec 1
#define INCLUDE_PI_AutoValue_RxConfigSpec 1
#include "$AutoValue_RxConfigSpec.h"

@interface PIAutoValue_RxConfigSpec : PI_AutoValue_RxConfigSpec

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)refresh
                    withInt:(jint)hb
                    withInt:(jint)fs_bc_interval
                    withInt:(jint)fs_bc_self_interval
                    withInt:(jint)a50_refresh_interval
                    withInt:(jint)a50_state_check_interval
                    withInt:(jint)ve_sync_play_interval
                    withInt:(jint)hb_timeout
                    withInt:(jint)rx_timeout
                    withInt:(jint)rx_retry
                withBoolean:(jboolean)play_one_auto_ve_change
                   withLong:(jlong)a50_inactive_threshold;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_RxConfigSpec)

FOUNDATION_EXPORT void PIAutoValue_RxConfigSpec_initWithInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withBoolean_withLong_(PIAutoValue_RxConfigSpec *self, jint refresh, jint hb, jint fs_bc_interval, jint fs_bc_self_interval, jint a50_refresh_interval, jint a50_state_check_interval, jint ve_sync_play_interval, jint hb_timeout, jint rx_timeout, jint rx_retry, jboolean play_one_auto_ve_change, jlong a50_inactive_threshold);

FOUNDATION_EXPORT PIAutoValue_RxConfigSpec *new_PIAutoValue_RxConfigSpec_initWithInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withBoolean_withLong_(jint refresh, jint hb, jint fs_bc_interval, jint fs_bc_self_interval, jint a50_refresh_interval, jint a50_state_check_interval, jint ve_sync_play_interval, jint hb_timeout, jint rx_timeout, jint rx_retry, jboolean play_one_auto_ve_change, jlong a50_inactive_threshold) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_RxConfigSpec *create_PIAutoValue_RxConfigSpec_initWithInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withBoolean_withLong_(jint refresh, jint hb, jint fs_bc_interval, jint fs_bc_self_interval, jint a50_refresh_interval, jint a50_state_check_interval, jint ve_sync_play_interval, jint hb_timeout, jint rx_timeout, jint rx_retry, jboolean play_one_auto_ve_change, jlong a50_inactive_threshold);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_RxConfigSpec)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_RxConfigSpec PIAutoValue_RxConfigSpec;

#endif

#if !defined (PIAutoValue_RxConfigSpec_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_RxConfigSpec || defined(INCLUDE_PIAutoValue_RxConfigSpec_GsonTypeAdapter))
#define PIAutoValue_RxConfigSpec_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PIRxConfigSpec;

@interface PIAutoValue_RxConfigSpec_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PIRxConfigSpec *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PIRxConfigSpec *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PIRxConfigSpec *)fromJsonWithNSString:(NSString *)arg0;

- (PIRxConfigSpec *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PIRxConfigSpec *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_RxConfigSpec_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_RxConfigSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_RxConfigSpec_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_RxConfigSpec_GsonTypeAdapter *new_PIAutoValue_RxConfigSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_RxConfigSpec_GsonTypeAdapter *create_PIAutoValue_RxConfigSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_RxConfigSpec_GsonTypeAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_AutoValue_RxConfigSpec")
