//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_ChangeRefreshRequestSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_ChangeRefreshRequestSpec")
#ifdef RESTRICT_AutoValue_ChangeRefreshRequestSpec
#define INCLUDE_ALL_AutoValue_ChangeRefreshRequestSpec 0
#else
#define INCLUDE_ALL_AutoValue_ChangeRefreshRequestSpec 1
#endif
#undef RESTRICT_AutoValue_ChangeRefreshRequestSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIAutoValue_ChangeRefreshRequestSpec_) && (INCLUDE_ALL_AutoValue_ChangeRefreshRequestSpec || defined(INCLUDE_PIAutoValue_ChangeRefreshRequestSpec))
#define PIAutoValue_ChangeRefreshRequestSpec_

#define RESTRICT_$AutoValue_ChangeRefreshRequestSpec 1
#define INCLUDE_PI_AutoValue_ChangeRefreshRequestSpec 1
#include "$AutoValue_ChangeRefreshRequestSpec.h"

@protocol JavaUtilList;

@interface PIAutoValue_ChangeRefreshRequestSpec : PI_AutoValue_ChangeRefreshRequestSpec

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)client_sdk_version
                    withNSString:(NSString *)device
                    withNSString:(NSString *)group_id
                    withNSString:(NSString *)uid
                    withNSString:(NSString *)ve_name
                         withInt:(jint)arrc
                     withBoolean:(jboolean)append
                withJavaUtilList:(id<JavaUtilList>)rooms
                    withNSString:(NSString *)merge_info
                    withNSString:(NSString *)split_info
                withJavaUtilList:(id<JavaUtilList>)us_caps
                    withNSString:(NSString *)mc_profile;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_ChangeRefreshRequestSpec)

FOUNDATION_EXPORT void PIAutoValue_ChangeRefreshRequestSpec_initWithNSString_withNSString_withNSString_withNSString_withNSString_withInt_withBoolean_withJavaUtilList_withNSString_withNSString_withJavaUtilList_withNSString_(PIAutoValue_ChangeRefreshRequestSpec *self, NSString *client_sdk_version, NSString *device, NSString *group_id, NSString *uid, NSString *ve_name, jint arrc, jboolean append, id<JavaUtilList> rooms, NSString *merge_info, NSString *split_info, id<JavaUtilList> us_caps, NSString *mc_profile);

FOUNDATION_EXPORT PIAutoValue_ChangeRefreshRequestSpec *new_PIAutoValue_ChangeRefreshRequestSpec_initWithNSString_withNSString_withNSString_withNSString_withNSString_withInt_withBoolean_withJavaUtilList_withNSString_withNSString_withJavaUtilList_withNSString_(NSString *client_sdk_version, NSString *device, NSString *group_id, NSString *uid, NSString *ve_name, jint arrc, jboolean append, id<JavaUtilList> rooms, NSString *merge_info, NSString *split_info, id<JavaUtilList> us_caps, NSString *mc_profile) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_ChangeRefreshRequestSpec *create_PIAutoValue_ChangeRefreshRequestSpec_initWithNSString_withNSString_withNSString_withNSString_withNSString_withInt_withBoolean_withJavaUtilList_withNSString_withNSString_withJavaUtilList_withNSString_(NSString *client_sdk_version, NSString *device, NSString *group_id, NSString *uid, NSString *ve_name, jint arrc, jboolean append, id<JavaUtilList> rooms, NSString *merge_info, NSString *split_info, id<JavaUtilList> us_caps, NSString *mc_profile);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_ChangeRefreshRequestSpec)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_ChangeRefreshRequestSpec PIAutoValue_ChangeRefreshRequestSpec;

#endif

#if !defined (PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_ChangeRefreshRequestSpec || defined(INCLUDE_PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter))
#define PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PIChangeRefreshRequestSpec;

@interface PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PIChangeRefreshRequestSpec *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PIChangeRefreshRequestSpec *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PIChangeRefreshRequestSpec *)fromJsonWithNSString:(NSString *)arg0;

- (PIChangeRefreshRequestSpec *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PIChangeRefreshRequestSpec *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter *new_PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter *create_PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_ChangeRefreshRequestSpec_GsonTypeAdapter)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AutoValue_ChangeRefreshRequestSpec")
