//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_CmdSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_CmdSpec")
#ifdef RESTRICT_AutoValue_CmdSpec
#define INCLUDE_ALL_AutoValue_CmdSpec 0
#else
#define INCLUDE_ALL_AutoValue_CmdSpec 1
#endif
#undef RESTRICT_AutoValue_CmdSpec

#if !defined (PIAutoValue_CmdSpec_) && (INCLUDE_ALL_AutoValue_CmdSpec || defined(INCLUDE_PIAutoValue_CmdSpec))
#define PIAutoValue_CmdSpec_

#define RESTRICT_$AutoValue_CmdSpec 1
#define INCLUDE_PI_AutoValue_CmdSpec 1
#include "$AutoValue_CmdSpec.h"

@interface PIAutoValue_CmdSpec : PI_AutoValue_CmdSpec

#pragma mark Package-Private

- (instancetype)initWithLong:(jlong)rid
                withNSString:(NSString *)srid
                withNSString:(NSString *)cmd;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_CmdSpec)

FOUNDATION_EXPORT void PIAutoValue_CmdSpec_initWithLong_withNSString_withNSString_(PIAutoValue_CmdSpec *self, jlong rid, NSString *srid, NSString *cmd);

FOUNDATION_EXPORT PIAutoValue_CmdSpec *new_PIAutoValue_CmdSpec_initWithLong_withNSString_withNSString_(jlong rid, NSString *srid, NSString *cmd) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_CmdSpec *create_PIAutoValue_CmdSpec_initWithLong_withNSString_withNSString_(jlong rid, NSString *srid, NSString *cmd);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_CmdSpec)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_CmdSpec PIAutoValue_CmdSpec;

#endif

#if !defined (PIAutoValue_CmdSpec_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_CmdSpec || defined(INCLUDE_PIAutoValue_CmdSpec_GsonTypeAdapter))
#define PIAutoValue_CmdSpec_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PICmdSpec;

@interface PIAutoValue_CmdSpec_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PICmdSpec *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PICmdSpec *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PICmdSpec *)fromJsonWithNSString:(NSString *)arg0;

- (PICmdSpec *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PICmdSpec *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_CmdSpec_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_CmdSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_CmdSpec_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_CmdSpec_GsonTypeAdapter *new_PIAutoValue_CmdSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_CmdSpec_GsonTypeAdapter *create_PIAutoValue_CmdSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_CmdSpec_GsonTypeAdapter)

#endif

#pragma pop_macro("INCLUDE_ALL_AutoValue_CmdSpec")
