//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_Cap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_Cap")
#ifdef RESTRICT_AutoValue_Cap
#define INCLUDE_ALL_AutoValue_Cap 0
#else
#define INCLUDE_ALL_AutoValue_Cap 1
#endif
#undef RESTRICT_AutoValue_Cap

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIAutoValue_Cap_) && (INCLUDE_ALL_AutoValue_Cap || defined(INCLUDE_PIAutoValue_Cap))
#define PIAutoValue_Cap_

#define RESTRICT_$AutoValue_Cap 1
#define INCLUDE_PI_AutoValue_Cap 1
#include "$AutoValue_Cap.h"

@class PICap_User;

@interface PIAutoValue_Cap : PI_AutoValue_Cap

#pragma mark Package-Private

- (instancetype)initWithPICap_User:(PICap_User *)to_user
                    withPICap_User:(PICap_User *)from_user
                           withInt:(jint)cap
                          withLong:(jlong)time;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_Cap)

FOUNDATION_EXPORT void PIAutoValue_Cap_initWithPICap_User_withPICap_User_withInt_withLong_(PIAutoValue_Cap *self, PICap_User *to_user, PICap_User *from_user, jint cap, jlong time);

FOUNDATION_EXPORT PIAutoValue_Cap *new_PIAutoValue_Cap_initWithPICap_User_withPICap_User_withInt_withLong_(PICap_User *to_user, PICap_User *from_user, jint cap, jlong time) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_Cap *create_PIAutoValue_Cap_initWithPICap_User_withPICap_User_withInt_withLong_(PICap_User *to_user, PICap_User *from_user, jint cap, jlong time);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_Cap)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_Cap PIAutoValue_Cap;

#endif

#if !defined (PIAutoValue_Cap_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_Cap || defined(INCLUDE_PIAutoValue_Cap_GsonTypeAdapter))
#define PIAutoValue_Cap_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PICap;

@interface PIAutoValue_Cap_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PICap *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PICap *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PICap *)fromJsonWithNSString:(NSString *)arg0;

- (PICap *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PICap *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_Cap_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_Cap_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_Cap_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_Cap_GsonTypeAdapter *new_PIAutoValue_Cap_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_Cap_GsonTypeAdapter *create_PIAutoValue_Cap_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_Cap_GsonTypeAdapter)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AutoValue_Cap")
