//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_MergeInfoSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_MergeInfoSpec")
#ifdef RESTRICT_AutoValue_MergeInfoSpec
#define INCLUDE_ALL_AutoValue_MergeInfoSpec 0
#else
#define INCLUDE_ALL_AutoValue_MergeInfoSpec 1
#endif
#undef RESTRICT_AutoValue_MergeInfoSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIAutoValue_MergeInfoSpec_) && (INCLUDE_ALL_AutoValue_MergeInfoSpec || defined(INCLUDE_PIAutoValue_MergeInfoSpec))
#define PIAutoValue_MergeInfoSpec_

#define RESTRICT_$AutoValue_MergeInfoSpec 1
#define INCLUDE_PI_AutoValue_MergeInfoSpec 1
#include "$AutoValue_MergeInfoSpec.h"

@class JavaUtilArrayList;

@interface PIAutoValue_MergeInfoSpec : PI_AutoValue_MergeInfoSpec

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)primary_sroom
           withJavaUtilArrayList:(JavaUtilArrayList *)srooms;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_MergeInfoSpec)

FOUNDATION_EXPORT void PIAutoValue_MergeInfoSpec_initWithNSString_withJavaUtilArrayList_(PIAutoValue_MergeInfoSpec *self, NSString *primary_sroom, JavaUtilArrayList *srooms);

FOUNDATION_EXPORT PIAutoValue_MergeInfoSpec *new_PIAutoValue_MergeInfoSpec_initWithNSString_withJavaUtilArrayList_(NSString *primary_sroom, JavaUtilArrayList *srooms) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_MergeInfoSpec *create_PIAutoValue_MergeInfoSpec_initWithNSString_withJavaUtilArrayList_(NSString *primary_sroom, JavaUtilArrayList *srooms);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_MergeInfoSpec)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_MergeInfoSpec PIAutoValue_MergeInfoSpec;

#endif

#if !defined (PIAutoValue_MergeInfoSpec_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_MergeInfoSpec || defined(INCLUDE_PIAutoValue_MergeInfoSpec_GsonTypeAdapter))
#define PIAutoValue_MergeInfoSpec_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PIMergeInfoSpec;

@interface PIAutoValue_MergeInfoSpec_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PIMergeInfoSpec *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PIMergeInfoSpec *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PIMergeInfoSpec *)fromJsonWithNSString:(NSString *)arg0;

- (PIMergeInfoSpec *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PIMergeInfoSpec *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_MergeInfoSpec_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_MergeInfoSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_MergeInfoSpec_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_MergeInfoSpec_GsonTypeAdapter *new_PIAutoValue_MergeInfoSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_MergeInfoSpec_GsonTypeAdapter *create_PIAutoValue_MergeInfoSpec_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_MergeInfoSpec_GsonTypeAdapter)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AutoValue_MergeInfoSpec")
