//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/AutoValue_PlayerStatusInfo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoValue_PlayerStatusInfo")
#ifdef RESTRICT_AutoValue_PlayerStatusInfo
#define INCLUDE_ALL_AutoValue_PlayerStatusInfo 0
#else
#define INCLUDE_ALL_AutoValue_PlayerStatusInfo 1
#endif
#undef RESTRICT_AutoValue_PlayerStatusInfo

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIAutoValue_PlayerStatusInfo_) && (INCLUDE_ALL_AutoValue_PlayerStatusInfo || defined(INCLUDE_PIAutoValue_PlayerStatusInfo))
#define PIAutoValue_PlayerStatusInfo_

#define RESTRICT_$AutoValue_PlayerStatusInfo 1
#define INCLUDE_PI_AutoValue_PlayerStatusInfo 1
#include "$AutoValue_PlayerStatusInfo.h"

@interface PIAutoValue_PlayerStatusInfo : PI_AutoValue_PlayerStatusInfo

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)uid
                    withNSString:(NSString *)ve_name
                         withInt:(jint)pzvt_delay;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_PlayerStatusInfo)

FOUNDATION_EXPORT void PIAutoValue_PlayerStatusInfo_initWithNSString_withNSString_withInt_(PIAutoValue_PlayerStatusInfo *self, NSString *uid, NSString *ve_name, jint pzvt_delay);

FOUNDATION_EXPORT PIAutoValue_PlayerStatusInfo *new_PIAutoValue_PlayerStatusInfo_initWithNSString_withNSString_withInt_(NSString *uid, NSString *ve_name, jint pzvt_delay) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_PlayerStatusInfo *create_PIAutoValue_PlayerStatusInfo_initWithNSString_withNSString_withInt_(NSString *uid, NSString *ve_name, jint pzvt_delay);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_PlayerStatusInfo)

@compatibility_alias ComPowerinfoPi_iroomDataAutoValue_PlayerStatusInfo PIAutoValue_PlayerStatusInfo;

#endif

#if !defined (PIAutoValue_PlayerStatusInfo_GsonTypeAdapter_) && (INCLUDE_ALL_AutoValue_PlayerStatusInfo || defined(INCLUDE_PIAutoValue_PlayerStatusInfo_GsonTypeAdapter))
#define PIAutoValue_PlayerStatusInfo_GsonTypeAdapter_

#define RESTRICT_TypeAdapter 1
#define INCLUDE_ComGoogleGsonTypeAdapter 1
#include "TypeAdapter.h"

@class ComGoogleGsonGson;
@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoReader;
@class PIPlayerStatusInfo;

@interface PIAutoValue_PlayerStatusInfo_GsonTypeAdapter : ComGoogleGsonTypeAdapter

#pragma mark Public

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (PIPlayerStatusInfo *)fromJsonTreeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)arg0;

- (PIPlayerStatusInfo *)fromJsonWithJavaIoReader:(JavaIoReader *)arg0;

- (PIPlayerStatusInfo *)fromJsonWithNSString:(NSString *)arg0;

- (PIPlayerStatusInfo *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)jsonReader;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)jsonWriter
                                        withId:(PIPlayerStatusInfo *)object;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIAutoValue_PlayerStatusInfo_GsonTypeAdapter)

FOUNDATION_EXPORT void PIAutoValue_PlayerStatusInfo_GsonTypeAdapter_initWithComGoogleGsonGson_(PIAutoValue_PlayerStatusInfo_GsonTypeAdapter *self, ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIAutoValue_PlayerStatusInfo_GsonTypeAdapter *new_PIAutoValue_PlayerStatusInfo_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIAutoValue_PlayerStatusInfo_GsonTypeAdapter *create_PIAutoValue_PlayerStatusInfo_GsonTypeAdapter_initWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

J2OBJC_TYPE_LITERAL_HEADER(PIAutoValue_PlayerStatusInfo_GsonTypeAdapter)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AutoValue_PlayerStatusInfo")
