//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/Cap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Cap")
#ifdef RESTRICT_Cap
#define INCLUDE_ALL_Cap 0
#else
#define INCLUDE_ALL_Cap 1
#endif
#undef RESTRICT_Cap

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PICap_) && (INCLUDE_ALL_Cap || defined(INCLUDE_PICap))
#define PICap_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;
@class PICap_User;

@interface PICap : NSObject

#pragma mark Public

- (instancetype)init;

- (jint)cap;

+ (PICap *)createWithPICap_User:(PICap_User *)to_user
                 withPICap_User:(PICap_User *)from_user
                        withInt:(jint)cap
                       withLong:(jlong)time;

- (PICap_User *)from_user;

- (PICap *)setCapWithInt:(jint)cap;

- (jlong)time;

- (PICap_User *)to_user;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

@end

J2OBJC_EMPTY_STATIC_INIT(PICap)

FOUNDATION_EXPORT void PICap_init(PICap *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PICap_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PICap *PICap_createWithPICap_User_withPICap_User_withInt_withLong_(PICap_User *to_user, PICap_User *from_user, jint cap, jlong time);

J2OBJC_TYPE_LITERAL_HEADER(PICap)

@compatibility_alias ComPowerinfoPi_iroomDataCap PICap;

#endif

#if !defined (PICap_User_) && (INCLUDE_ALL_Cap || defined(INCLUDE_PICap_User))
#define PICap_User_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;

@interface PICap_User : NSObject

#pragma mark Public

- (instancetype)init;

+ (PICap_User *)createWithNSString:(NSString *)uid
                      withNSString:(NSString *)veName;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (NSString *)uid;

- (NSString *)ve_name;

@end

J2OBJC_EMPTY_STATIC_INIT(PICap_User)

FOUNDATION_EXPORT void PICap_User_init(PICap_User *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PICap_User_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PICap_User *PICap_User_createWithNSString_withNSString_(NSString *uid, NSString *veName);

J2OBJC_TYPE_LITERAL_HEADER(PICap_User)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_Cap")
