//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/ChangeRefreshRequestSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ChangeRefreshRequestSpec")
#ifdef RESTRICT_ChangeRefreshRequestSpec
#define INCLUDE_ALL_ChangeRefreshRequestSpec 0
#else
#define INCLUDE_ALL_ChangeRefreshRequestSpec 1
#endif
#undef RESTRICT_ChangeRefreshRequestSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIChangeRefreshRequestSpec_) && (INCLUDE_ALL_ChangeRefreshRequestSpec || defined(INCLUDE_PIChangeRefreshRequestSpec))
#define PIChangeRefreshRequestSpec_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;
@protocol JavaUtilList;

@interface PIChangeRefreshRequestSpec : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)append;

- (jint)arrc;

+ (PIChangeRefreshRequestSpec *)initWithSdkVersion:(NSString *)clientSdkVersion
                                          deviceId:(NSString *)deviceId
                                           groupId:(NSString *)groupId
                                               uid:(NSString *)uid
                                            append:(jboolean)append
                                              cmds:(id<JavaUtilList>)cmds
                                         mergeInfo:(NSString *)mergeInfo
                                         splitInfo:(NSString *)splitInfo OBJC_METHOD_FAMILY_NONE;

+ (PIChangeRefreshRequestSpec *)initWithSdkVersion:(NSString *)clientSdkVersion
                                          deviceId:(NSString *)deviceId
                                           groupId:(NSString *)groupId
                                               uid:(NSString *)uid
                                            veName:(NSString *)veName
                                            append:(jboolean)append
                                              cmds:(id<JavaUtilList>)cmds
                                         mergeInfo:(NSString *)mergeInfo
                                         splitInfo:(NSString *)splitInfo OBJC_METHOD_FAMILY_NONE;

+ (PIChangeRefreshRequestSpec *)initWithSdkVersion:(NSString *)clientSdkVersion
                                          deviceId:(NSString *)deviceId
                                           groupId:(NSString *)groupId
                                               uid:(NSString *)uid
                                            veName:(NSString *)veName
                                            append:(jboolean)append
                                              cmds:(id<JavaUtilList>)cmds
                                         mergeInfo:(NSString *)mergeInfo
                                         splitInfo:(NSString *)splitInfo
                                         mcProfile:(NSString *)mcProfile OBJC_METHOD_FAMILY_NONE;

- (NSString *)client_sdk_version;

- (NSString *)device;

- (NSString *)group_id;

- (NSString *)mc_profile;

- (NSString *)merge_info;

+ (PIChangeRefreshRequestSpec *)initWithSdkVersion:(NSString *)clientSdkVersion
                                          deviceId:(NSString *)deviceId
                                           groupId:(NSString *)groupId
                                               uid:(NSString *)uid OBJC_METHOD_FAMILY_NONE;

+ (PIChangeRefreshRequestSpec *)initWithSdkVersion:(NSString *)clientSdkVersion
                                          deviceId:(NSString *)deviceId
                                           groupId:(NSString *)groupId
                                               uid:(NSString *)uid
                                            veName:(NSString *)veName OBJC_METHOD_FAMILY_NONE;

+ (PIChangeRefreshRequestSpec *)initWithSdkVersion:(NSString *)clientSdkVersion
                                          deviceId:(NSString *)deviceId
                                           groupId:(NSString *)groupId
                                               uid:(NSString *)uid
                                            veName:(NSString *)veName
                                              caps:(id<JavaUtilList>)caps OBJC_METHOD_FAMILY_NONE;

- (id<JavaUtilList>)rooms;

- (NSString *)split_info;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (NSString *)uid;

- (id<JavaUtilList>)us_caps;

- (NSString *)ve_name;

@end

J2OBJC_EMPTY_STATIC_INIT(PIChangeRefreshRequestSpec)

FOUNDATION_EXPORT void PIChangeRefreshRequestSpec_init(PIChangeRefreshRequestSpec *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PIChangeRefreshRequestSpec_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIChangeRefreshRequestSpec *PIChangeRefreshRequestSpec_initWithSdkVersion_deviceId_groupId_uid_append_cmds_mergeInfo_splitInfo_(NSString *clientSdkVersion, NSString *deviceId, NSString *groupId, NSString *uid, jboolean append, id<JavaUtilList> cmds, NSString *mergeInfo, NSString *splitInfo);

FOUNDATION_EXPORT PIChangeRefreshRequestSpec *PIChangeRefreshRequestSpec_initWithSdkVersion_deviceId_groupId_uid_veName_append_cmds_mergeInfo_splitInfo_(NSString *clientSdkVersion, NSString *deviceId, NSString *groupId, NSString *uid, NSString *veName, jboolean append, id<JavaUtilList> cmds, NSString *mergeInfo, NSString *splitInfo);

FOUNDATION_EXPORT PIChangeRefreshRequestSpec *PIChangeRefreshRequestSpec_initWithSdkVersion_deviceId_groupId_uid_veName_append_cmds_mergeInfo_splitInfo_mcProfile_(NSString *clientSdkVersion, NSString *deviceId, NSString *groupId, NSString *uid, NSString *veName, jboolean append, id<JavaUtilList> cmds, NSString *mergeInfo, NSString *splitInfo, NSString *mcProfile);

FOUNDATION_EXPORT PIChangeRefreshRequestSpec *PIChangeRefreshRequestSpec_initWithSdkVersion_deviceId_groupId_uid_veName_caps_(NSString *clientSdkVersion, NSString *deviceId, NSString *groupId, NSString *uid, NSString *veName, id<JavaUtilList> caps);

FOUNDATION_EXPORT PIChangeRefreshRequestSpec *PIChangeRefreshRequestSpec_initWithSdkVersion_deviceId_groupId_uid_(NSString *clientSdkVersion, NSString *deviceId, NSString *groupId, NSString *uid);

FOUNDATION_EXPORT PIChangeRefreshRequestSpec *PIChangeRefreshRequestSpec_initWithSdkVersion_deviceId_groupId_uid_veName_(NSString *clientSdkVersion, NSString *deviceId, NSString *groupId, NSString *uid, NSString *veName);

J2OBJC_TYPE_LITERAL_HEADER(PIChangeRefreshRequestSpec)

@compatibility_alias ComPowerinfoPi_iroomDataChangeRefreshRequestSpec PIChangeRefreshRequestSpec;

#endif

#if !defined (PIChangeRefreshRequestSpec_Builder_) && (INCLUDE_ALL_ChangeRefreshRequestSpec || defined(INCLUDE_PIChangeRefreshRequestSpec_Builder))
#define PIChangeRefreshRequestSpec_Builder_

@class PIChangeRefreshRequestSpec;
@protocol JavaUtilList;

@interface PIChangeRefreshRequestSpec_Builder : NSObject

#pragma mark Public

- (instancetype)init;

- (PIChangeRefreshRequestSpec_Builder *)append:(jboolean)append;

- (PIChangeRefreshRequestSpec_Builder *)arrc:(jint)arrc;

- (PIChangeRefreshRequestSpec *)Builder;

- (PIChangeRefreshRequestSpec_Builder *)client_sdk_version:(NSString *)client_sdk_version;

- (PIChangeRefreshRequestSpec_Builder *)device:(NSString *)device;

- (PIChangeRefreshRequestSpec_Builder *)group_id:(NSString *)group_id;

- (PIChangeRefreshRequestSpec_Builder *)mc_profile:(NSString *)mc_profile;

- (PIChangeRefreshRequestSpec_Builder *)merge_info:(NSString *)merge_info;

- (PIChangeRefreshRequestSpec_Builder *)rooms:(id<JavaUtilList>)rooms;

- (PIChangeRefreshRequestSpec_Builder *)split_info:(NSString *)split_info;

- (PIChangeRefreshRequestSpec_Builder *)uid:(NSString *)uid;

- (PIChangeRefreshRequestSpec_Builder *)us_caps:(id<JavaUtilList>)us_caps;

- (PIChangeRefreshRequestSpec_Builder *)ve_name:(NSString *)ve_name;

@end

J2OBJC_EMPTY_STATIC_INIT(PIChangeRefreshRequestSpec_Builder)

FOUNDATION_EXPORT void PIChangeRefreshRequestSpec_Builder_init(PIChangeRefreshRequestSpec_Builder *self);

J2OBJC_TYPE_LITERAL_HEADER(PIChangeRefreshRequestSpec_Builder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ChangeRefreshRequestSpec")
