//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/ChangeRefreshResultSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ChangeRefreshResultSpec")
#ifdef RESTRICT_ChangeRefreshResultSpec
#define INCLUDE_ALL_ChangeRefreshResultSpec 0
#else
#define INCLUDE_ALL_ChangeRefreshResultSpec 1
#endif
#undef RESTRICT_ChangeRefreshResultSpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIChangeRefreshResultSpec_) && (INCLUDE_ALL_ChangeRefreshResultSpec || defined(INCLUDE_PIChangeRefreshResultSpec))
#define PIChangeRefreshResultSpec_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;
@class PIChangeRefreshResultSpec_Builder;
@class PIChangeRefreshResultSpec_Sig;
@class PIRxConfigSpec;
@class PISigCmd;
@protocol JavaUtilList;

@interface PIChangeRefreshResultSpec : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)app_private_data;

+ (PIChangeRefreshResultSpec_Builder *)builder;

+ (PIChangeRefreshResultSpec *)createPreloadResultWithCreatorUid:(NSString *)creatorUid
                                                      withRoomId:(NSString *)roomId
                                              withPlayStreamMode:(jint)playStreamMode
                                                         withUrl:(NSString *)url;

- (jint)enable_ve_opt;

- (id<JavaUtilList>)getActsSafely;

- (id<JavaUtilList>)getJoinedRoomsSafely;

- (id<JavaUtilList>)getPlayTargetsSafely;

- (id<JavaUtilList>)getPushTargetsSafely;

- (id<JavaUtilList>)getStreamEventCmdsSafely;

- (id<JavaUtilList>)joined_srooms;

- (NSString *)mc_global_params;

- (id<JavaUtilList>)play_targets;

- (id<JavaUtilList>)push_targets;

- (jint)refresh;

- (jint)rs_result;

- (PIRxConfigSpec *)rx_config;

- (jint)scene_play_type;

- (PIChangeRefreshResultSpec_Sig *)sig;

- (PISigCmd *)sigcmd;

- (jint)status_policy;

- (id<JavaUtilList>)stream_event_cmd;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (id<JavaUtilList>)us_acts;

@end

J2OBJC_EMPTY_STATIC_INIT(PIChangeRefreshResultSpec)

inline jint PIChangeRefreshResultSpec_get_ENABLE_VE_OPT(void);
#define PIChangeRefreshResultSpec_ENABLE_VE_OPT 1
J2OBJC_STATIC_FIELD_CONSTANT(PIChangeRefreshResultSpec, ENABLE_VE_OPT, jint)

FOUNDATION_EXPORT void PIChangeRefreshResultSpec_init(PIChangeRefreshResultSpec *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PIChangeRefreshResultSpec_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIChangeRefreshResultSpec_Builder *PIChangeRefreshResultSpec_builder(void);

FOUNDATION_EXPORT PIChangeRefreshResultSpec *PIChangeRefreshResultSpec_createPreloadResultWithCreatorUid_withRoomId_withPlayStreamMode_withUrl_(NSString *creatorUid, NSString *roomId, jint playStreamMode, NSString *url);

J2OBJC_TYPE_LITERAL_HEADER(PIChangeRefreshResultSpec)

@compatibility_alias ComPowerinfoPi_iroomDataChangeRefreshResultSpec PIChangeRefreshResultSpec;

#endif

#if !defined (PIChangeRefreshResultSpec_Builder_) && (INCLUDE_ALL_ChangeRefreshResultSpec || defined(INCLUDE_PIChangeRefreshResultSpec_Builder))
#define PIChangeRefreshResultSpec_Builder_

@class PIChangeRefreshResultSpec;
@class PIChangeRefreshResultSpec_Sig;
@class PIRxConfigSpec;
@class PISigCmd;
@protocol JavaUtilList;

@interface PIChangeRefreshResultSpec_Builder : NSObject

#pragma mark Public

- (instancetype)init;

- (PIChangeRefreshResultSpec_Builder *)app_private_data:(NSString *)app_private_data;

- (PIChangeRefreshResultSpec *)build;

- (PIChangeRefreshResultSpec_Builder *)enable_ve_opt:(jint)enable_ve_opt;

- (PIChangeRefreshResultSpec_Builder *)joined_srooms:(id<JavaUtilList>)joined_rooms;

- (PIChangeRefreshResultSpec_Builder *)mc_global_params:(NSString *)mc_global_params;

- (PIChangeRefreshResultSpec_Builder *)play_targets:(id<JavaUtilList>)play_targets;

- (PIChangeRefreshResultSpec_Builder *)push_targets:(id<JavaUtilList>)push_targets;

- (PIChangeRefreshResultSpec_Builder *)refresh:(jint)refresh;

- (PIChangeRefreshResultSpec_Builder *)rs_result:(jint)rs_result;

- (PIChangeRefreshResultSpec_Builder *)rx_config:(PIRxConfigSpec *)rx_config;

- (PIChangeRefreshResultSpec_Builder *)scene_play_type:(jint)scene_play_type;

- (PIChangeRefreshResultSpec_Builder *)sig:(PIChangeRefreshResultSpec_Sig *)sig;

- (PIChangeRefreshResultSpec_Builder *)sigcmd:(PISigCmd *)sigcmd;

- (PIChangeRefreshResultSpec_Builder *)status_policy:(jint)status_policy;

- (PIChangeRefreshResultSpec_Builder *)stream_event_cmd:(id<JavaUtilList>)stream_event_cmd;

- (PIChangeRefreshResultSpec_Builder *)us_acts:(id<JavaUtilList>)us_acts;

@end

J2OBJC_EMPTY_STATIC_INIT(PIChangeRefreshResultSpec_Builder)

FOUNDATION_EXPORT void PIChangeRefreshResultSpec_Builder_init(PIChangeRefreshResultSpec_Builder *self);

J2OBJC_TYPE_LITERAL_HEADER(PIChangeRefreshResultSpec_Builder)

#endif

#if !defined (PIChangeRefreshResultSpec_Sig_) && (INCLUDE_ALL_ChangeRefreshResultSpec || defined(INCLUDE_PIChangeRefreshResultSpec_Sig))
#define PIChangeRefreshResultSpec_Sig_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;
@class PIChangeRefreshResultSpec_Sig_Builder;

@interface PIChangeRefreshResultSpec_Sig : NSObject

#pragma mark Public

- (instancetype)init;

+ (PIChangeRefreshResultSpec_Sig_Builder *)builder;

+ (PIChangeRefreshResultSpec_Sig *)createWithNSString:(NSString *)url
                                              withInt:(jint)timeout
                                              withInt:(jint)reconnection_attempts
                                              withInt:(jint)reconnection_delay;

- (jint)reconnection_attempts;

- (jint)reconnection_delay;

- (jint)timeout;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (NSString *)url;

@end

J2OBJC_EMPTY_STATIC_INIT(PIChangeRefreshResultSpec_Sig)

FOUNDATION_EXPORT void PIChangeRefreshResultSpec_Sig_init(PIChangeRefreshResultSpec_Sig *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PIChangeRefreshResultSpec_Sig_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIChangeRefreshResultSpec_Sig *PIChangeRefreshResultSpec_Sig_createWithNSString_withInt_withInt_withInt_(NSString *url, jint timeout, jint reconnection_attempts, jint reconnection_delay);

FOUNDATION_EXPORT PIChangeRefreshResultSpec_Sig_Builder *PIChangeRefreshResultSpec_Sig_builder(void);

J2OBJC_TYPE_LITERAL_HEADER(PIChangeRefreshResultSpec_Sig)

#endif

#if !defined (PIChangeRefreshResultSpec_Sig_Builder_) && (INCLUDE_ALL_ChangeRefreshResultSpec || defined(INCLUDE_PIChangeRefreshResultSpec_Sig_Builder))
#define PIChangeRefreshResultSpec_Sig_Builder_

@class PIChangeRefreshResultSpec_Sig;

@interface PIChangeRefreshResultSpec_Sig_Builder : NSObject

#pragma mark Public

- (instancetype)init;

- (PIChangeRefreshResultSpec_Sig *)build;

- (PIChangeRefreshResultSpec_Sig_Builder *)reconnection_attempts:(jint)reconnection_attempts;

- (PIChangeRefreshResultSpec_Sig_Builder *)reconnection_delay:(jint)reconnection_delay;

- (PIChangeRefreshResultSpec_Sig_Builder *)timeout:(jint)timeout;

- (PIChangeRefreshResultSpec_Sig_Builder *)url:(NSString *)url;

@end

J2OBJC_EMPTY_STATIC_INIT(PIChangeRefreshResultSpec_Sig_Builder)

FOUNDATION_EXPORT void PIChangeRefreshResultSpec_Sig_Builder_init(PIChangeRefreshResultSpec_Sig_Builder *self);

J2OBJC_TYPE_LITERAL_HEADER(PIChangeRefreshResultSpec_Sig_Builder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ChangeRefreshResultSpec")
