//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/CheckedUser.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CheckedUser")
#ifdef RESTRICT_CheckedUser
#define INCLUDE_ALL_CheckedUser 0
#else
#define INCLUDE_ALL_CheckedUser 1
#endif
#undef RESTRICT_CheckedUser

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PICheckedUser_) && (INCLUDE_ALL_CheckedUser || defined(INCLUDE_PICheckedUser))
#define PICheckedUser_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;

@interface PICheckedUser : NSObject

#pragma mark Public

- (instancetype)init;

+ (PICheckedUser *)createCheckedUserWithUid:(NSString *)uid
                                 withVeName:(NSString *)ve_name;

- (jboolean)streaming;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (NSString *)uid;

- (NSString *)ve_name;

@end

J2OBJC_EMPTY_STATIC_INIT(PICheckedUser)

FOUNDATION_EXPORT void PICheckedUser_init(PICheckedUser *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PICheckedUser_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PICheckedUser *PICheckedUser_createCheckedUserWithUid_withVeName_(NSString *uid, NSString *ve_name);

J2OBJC_TYPE_LITERAL_HEADER(PICheckedUser)

@compatibility_alias ComPowerinfoPi_iroomDataCheckedUser PICheckedUser;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_CheckedUser")
