//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/CmdSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CmdSpec")
#ifdef RESTRICT_CmdSpec
#define INCLUDE_ALL_CmdSpec 0
#else
#define INCLUDE_ALL_CmdSpec 1
#endif
#undef RESTRICT_CmdSpec

#if !defined (PICmdSpec_) && (INCLUDE_ALL_CmdSpec || defined(INCLUDE_PICmdSpec))
#define PICmdSpec_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;

@interface PICmdSpec : NSObject

#pragma mark Public

- (instancetype)init;

- (NSString *)cmd;

+ (PICmdSpec *)createWithLong:(jlong)rid
                 withNSString:(NSString *)cmd;

+ (PICmdSpec *)createWithRid:(NSString *)rid
                     withCmd:(NSString *)cmd;

- (NSString *)getSrid;

- (jlong)rid;

- (NSString *)srid;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

@end

J2OBJC_EMPTY_STATIC_INIT(PICmdSpec)

FOUNDATION_EXPORT void PICmdSpec_init(PICmdSpec *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PICmdSpec_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PICmdSpec *PICmdSpec_createWithLong_withNSString_(jlong rid, NSString *cmd);

FOUNDATION_EXPORT PICmdSpec *PICmdSpec_createWithRid_withCmd_(NSString *rid, NSString *cmd);

J2OBJC_TYPE_LITERAL_HEADER(PICmdSpec)

@compatibility_alias ComPowerinfoPi_iroomDataCmdSpec PICmdSpec;

#endif

#pragma pop_macro("INCLUDE_ALL_CmdSpec")
