//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/CmdTargetSpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CmdTargetSpec")
#ifdef RESTRICT_CmdTargetSpec
#define INCLUDE_ALL_CmdTargetSpec 0
#else
#define INCLUDE_ALL_CmdTargetSpec 1
#endif
#undef RESTRICT_CmdTargetSpec

#if !defined (PICmdTargetSpec_) && (INCLUDE_ALL_CmdTargetSpec || defined(INCLUDE_PICmdTargetSpec))
#define PICmdTargetSpec_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;

@interface PICmdTargetSpec : NSObject

#pragma mark Public

- (instancetype)init;

+ (PICmdTargetSpec *)createCmdTargetSpecWithUid:(NSString *)uid;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (NSString *)uid;

@end

J2OBJC_EMPTY_STATIC_INIT(PICmdTargetSpec)

FOUNDATION_EXPORT void PICmdTargetSpec_init(PICmdTargetSpec *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PICmdTargetSpec_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PICmdTargetSpec *PICmdTargetSpec_createCmdTargetSpecWithUid_(NSString *uid);

J2OBJC_TYPE_LITERAL_HEADER(PICmdTargetSpec)

@compatibility_alias ComPowerinfoPi_iroomDataCmdTargetSpec PICmdTargetSpec;

#endif

#pragma pop_macro("INCLUDE_ALL_CmdTargetSpec")
