//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/api/IjkPlayerApi.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IjkPlayerApi")
#ifdef RESTRICT_IjkPlayerApi
#define INCLUDE_ALL_IjkPlayerApi 0
#else
#define INCLUDE_ALL_IjkPlayerApi 1
#endif
#undef RESTRICT_IjkPlayerApi

#if !defined (PIIjkPlayerApi_) && (INCLUDE_ALL_IjkPlayerApi || defined(INCLUDE_PIIjkPlayerApi))
#define PIIjkPlayerApi_

@class PIPlayTargetSpec;
@class PIUsAct;
@class PIUsCapSpec;
@protocol JavaUtilList;
@protocol PIAction0;
@protocol PIScheduledScreenshotCallback;

@protocol PIIjkPlayerApi < JavaObject >

- (NSString *)getReceiveUrl;

- (NSString *)getPzbData;

- (void)startPlay;

- (void)restartWithResetUrl:(jboolean)resetUrl
                 withNewUrl:(NSString *)newUrl;

- (void)resume:(jint)audioInterrupt;

- (void)pause;

- (void)reconnect:(jboolean)connected;

- (void)retryNoWait;

- (void)stopPlay:(id<PIAction0>)onFinished;

- (void)toggleMute:(jboolean)isMute;

- (jlong)getExtraTs;

- (jboolean)startTimedRecord:(NSString *)path
                   startTime:(jlong)startTime
                    duration:(jint)duration;

- (jboolean)startRecord:(NSString *)path;

- (void)stopRecord;

- (void)updatePlayTarget:(PIPlayTargetSpec *)playTarget
                 isOneVe:(jboolean)isOneVe
                 setView:(jboolean)setView
        onlyChangeVeName:(jboolean)onlyChangeVeName
           pzbDataSource:(jint)pzbDataSource;

- (void)updatePushPlayStatus:(jboolean)hasPush;

- (jint)scheduleScreenshot:(jlong)pzvt
                      path:(NSString *)path
                  callback:(id<PIScheduledScreenshotCallback>)callback;

- (void)cancelScheduledScreenshot:(jint)id_;

- (void)takeUsAct:(PIUsAct *)act;

- (PIUsCapSpec *)getUsCap;

- (jint)sendEventToPusher:(NSString *)data;

- (jint)getArrcTarget;

- (void)setArrcTarget:(jint)size
          aarcTargets:(id<JavaUtilList>)aarcTargets;

- (jint)getStreamState;

- (jint)getPzvtDelay;

- (jlong)get4GUsage;

@end

J2OBJC_EMPTY_STATIC_INIT(PIIjkPlayerApi)

inline NSString *PIIjkPlayerApi_get_PROBE_DISABLE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PIIjkPlayerApi_PROBE_DISABLE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PIIjkPlayerApi, PROBE_DISABLE, NSString *)

inline jint PIIjkPlayerApi_get_PZB_DATA_SOURCE_RS(void);
#define PIIjkPlayerApi_PZB_DATA_SOURCE_RS 0
J2OBJC_STATIC_FIELD_CONSTANT(PIIjkPlayerApi, PZB_DATA_SOURCE_RS, jint)

inline jint PIIjkPlayerApi_get_PZB_DATA_SOURCE_SIG(void);
#define PIIjkPlayerApi_PZB_DATA_SOURCE_SIG 1
J2OBJC_STATIC_FIELD_CONSTANT(PIIjkPlayerApi, PZB_DATA_SOURCE_SIG, jint)

inline jint PIIjkPlayerApi_get_ADD_PLAYER_SOURCE_RS(void);
#define PIIjkPlayerApi_ADD_PLAYER_SOURCE_RS 1
J2OBJC_STATIC_FIELD_CONSTANT(PIIjkPlayerApi, ADD_PLAYER_SOURCE_RS, jint)

inline jint PIIjkPlayerApi_get_ADD_PLAYER_SOURCE_SIG(void);
#define PIIjkPlayerApi_ADD_PLAYER_SOURCE_SIG 2
J2OBJC_STATIC_FIELD_CONSTANT(PIIjkPlayerApi, ADD_PLAYER_SOURCE_SIG, jint)

J2OBJC_TYPE_LITERAL_HEADER(PIIjkPlayerApi)

#define ComPowerinfoPi_iroomApiIjkPlayerApi PIIjkPlayerApi

#endif

#if !defined (PIIjkPlayerCallback_) && (INCLUDE_ALL_IjkPlayerApi || defined(INCLUDE_PIIjkPlayerCallback))
#define PIIjkPlayerCallback_

@class PIPlayTargetSpec;

@protocol PIIjkPlayerCallback < JavaObject >

- (void)onReceiveAudioSuccess:(PIPlayTargetSpec *)playTarget;

- (void)onReceiveVideoSuccess:(PIPlayTargetSpec *)playTarget;

- (void)onReceiveEventFromPusher:(PIPlayTargetSpec *)playTarget
                         content:(NSString *)content;

- (void)onReReceiveSuccess;

- (void)onPlayerRestart;

- (void)onIJKNeedRetry:(jint)retryReason;

- (void)onViewChanged:(PIPlayTargetSpec *)playTarget
            newVeName:(NSString *)newVeName;

- (void)onChangeVeName:(NSString *)roomId
               withUid:(NSString *)uid
         withOldVeName:(NSString *)oldVeName
         withNewVeName:(NSString *)newVeName;

- (void)onVeChangeResult:(jint)result;

- (void)onCoreStatusResult:(PIPlayTargetSpec *)playTarget
           withContentType:(jint)contentType
               withContent:(NSString *)content;

@end

J2OBJC_EMPTY_STATIC_INIT(PIIjkPlayerCallback)

J2OBJC_TYPE_LITERAL_HEADER(PIIjkPlayerCallback)

#endif

#pragma pop_macro("INCLUDE_ALL_IjkPlayerApi")
