//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/utils/JsonConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonConverter")
#ifdef RESTRICT_JsonConverter
#define INCLUDE_ALL_JsonConverter 0
#else
#define INCLUDE_ALL_JsonConverter 1
#endif
#undef RESTRICT_JsonConverter

#if !defined (PIJsonConverter_) && (INCLUDE_ALL_JsonConverter || defined(INCLUDE_PIJsonConverter))
#define PIJsonConverter_

@class PIA50RefreshRequest;
@class PIA50RefreshResult;
@class PIA50StateEvent;
@class PIAddSynchronousEventData;
@class PIAliyunDNSResponse;
@class PIAppKey;
@class PICameraZoom;
@class PICancelSynchronousEventData;
@class PIChangeRefreshRequestSpec;
@class PIChangeRefreshResultSpec;
@class PICheckStreamingRequest;
@class PICheckStreamingResult;
@class PIConfigResult;
@class PIFunctionSeqRequest;
@class PIFunctionSeqResult;
@class PIIAEvent;
@class PIIAEventMsg;
@class PILegacyCmdSpec;
@class PIMergeInfoSpec;
@class PIMetronomeChannelConfigSpec;
@class PIMixMusicConfigSpec;
@class PIPreloadRequest;
@class PIReportAliveRequest;
@class PIReportAliveResult;
@class PISelfStateEvent;
@class PISigMessage;
@class PISplitInfoSpec;
@class PIStateEvent;
@class PIiRoomMessage;
@protocol JavaUtilList;
@protocol PILogger;

@interface PIJsonConverter : NSObject

#pragma mark Public

- (NSString *)A50RefreshRequestToJson:(PIA50RefreshRequest *)request;

- (NSString *)a50StateEventToJson:(PIA50StateEvent *)event;

- (NSString *)addSynchronousEventDataToJson:(PIAddSynchronousEventData *)data;

- (NSString *)appKeyToJson:(PIAppKey *)appKey;

- (NSString *)cameraZoomToJson:(PICameraZoom *)cameraZoom;

- (NSString *)cancelSynchronousEventDataToJson:(PICancelSynchronousEventData *)data;

- (NSString *)changeRefreshRequestToJson:(PIChangeRefreshRequestSpec *)request;

- (NSString *)changeRefreshResultToJson:(PIChangeRefreshResultSpec *)result;

- (NSString *)checkStreamingRequestToJson:(PICheckStreamingRequest *)request;

- (NSString *)functionSeqRequestToJson:(PIFunctionSeqRequest *)request;

+ (PIJsonConverter *)getInstanceWithLogger:(id<PILogger>)logger;

- (NSString *)iaEventMsgToJson:(PIIAEventMsg *)iaEventMsg;

- (NSString *)iaEventToJson:(PIIAEvent *)event;

- (NSString *)legacyCmdToJson:(PILegacyCmdSpec *)legacyCmd;

- (NSString *)mergeInfoToJson:(PIMergeInfoSpec *)mergeInfo;

- (NSString *)messageToJson:(PIiRoomMessage *)message;

- (NSString *)metronomeChannelConfigToJson:(PIMetronomeChannelConfigSpec *)metronomeChannelConfigSpec;

- (NSString *)mixMusicConfigToJson:(PIMixMusicConfigSpec *)mixMusicConfigSpec;

- (PIA50RefreshResult *)parseA50RefreshResult:(NSString *)json;

- (PIA50StateEvent *)parseA50StateData:(NSString *)json;

- (PIAddSynchronousEventData *)parseAddSynchronousEventData:(NSString *)json;

- (PIAliyunDNSResponse *)parseAliyunDNSResponse:(NSString *)json;

- (PIAppKey *)parseAppKey:(NSString *)appKey;

- (PICameraZoom *)parseCameraZoom:(NSString *)json;

- (PICancelSynchronousEventData *)parseCancelSynchronousEventData:(NSString *)json;

- (PIChangeRefreshResultSpec *)parseChangeRefreshResult:(NSString *)json;

- (id<JavaUtilList>)parseChangeRefreshResultList:(NSString *)json;

- (PICheckStreamingResult *)parseCheckStreamingResult:(NSString *)json;

- (PIConfigResult *)parseConfigResult:(NSString *)json;

- (PIFunctionSeqResult *)parseFunctionSeqResult:(NSString *)json;

- (PIIAEvent *)parseIAEvent:(NSString *)json;

- (PIIAEventMsg *)parseIAEventMsg:(NSString *)json;

- (PILegacyCmdSpec *)parseLegacyCmd:(NSString *)json;

- (PIiRoomMessage *)parseMessage:(NSString *)json;

- (PIMetronomeChannelConfigSpec *)parseMetronomeChannelConfig:(NSString *)json;

- (PIMixMusicConfigSpec *)parseMixMusicConfig:(NSString *)json;

- (PIReportAliveResult *)parseReportAliveResult:(NSString *)json;

- (PISelfStateEvent *)parseSelfStateEventData:(NSString *)json;

- (PISigMessage *)parseSigMessage:(NSString *)message;

- (PIStateEvent *)parseStateEventData:(NSString *)json;

- (NSString *)preloadRequestToJson:(PIPreloadRequest *)request;

- (NSString *)reportRequestToJson:(PIReportAliveRequest *)request;

- (NSString *)selfStateEventToJson:(PISelfStateEvent *)selfStateEvent;

- (NSString *)sigMessageToJson:(PISigMessage *)sigMessage;

- (NSString *)splitInfoToJson:(PISplitInfoSpec *)splitInfo;

- (NSString *)stateEventToJson:(PIStateEvent *)stateEvent;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIJsonConverter)

FOUNDATION_EXPORT PIJsonConverter *PIJsonConverter_getInstanceWithLogger_(id<PILogger> logger);

J2OBJC_TYPE_LITERAL_HEADER(PIJsonConverter)

@compatibility_alias ComPowerinfoPi_iroomUtilsJsonConverter PIJsonConverter;

#endif

#pragma pop_macro("INCLUDE_ALL_JsonConverter")
