//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/utils/LayoutController.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LayoutController")
#ifdef RESTRICT_LayoutController
#define INCLUDE_ALL_LayoutController 0
#else
#define INCLUDE_ALL_LayoutController 1
#endif
#undef RESTRICT_LayoutController

#if !defined (PILayoutController_) && (INCLUDE_ALL_LayoutController || defined(INCLUDE_PILayoutController))
#define PILayoutController_

@protocol PILayoutController < JavaObject >

- (id)createWindowContainer:(NSString *)rid
                        uid:(NSString *)uid
                     veName:(NSString *)veName;

@end

J2OBJC_EMPTY_STATIC_INIT(PILayoutController)

J2OBJC_TYPE_LITERAL_HEADER(PILayoutController)

#define ComPowerinfoPi_iroomUtilsLayoutController PILayoutController

#endif

#pragma pop_macro("INCLUDE_ALL_LayoutController")
