//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/api/LibraryVersionUtilApi.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LibraryVersionUtilApi")
#ifdef RESTRICT_LibraryVersionUtilApi
#define INCLUDE_ALL_LibraryVersionUtilApi 0
#else
#define INCLUDE_ALL_LibraryVersionUtilApi 1
#endif
#undef RESTRICT_LibraryVersionUtilApi

#if !defined (PILibraryVersionUtilApi_) && (INCLUDE_ALL_LibraryVersionUtilApi || defined(INCLUDE_PILibraryVersionUtilApi))
#define PILibraryVersionUtilApi_

@protocol PILibraryVersionUtilApi < JavaObject >

- (NSString *)getiRoomVersion;

- (NSString *)getTranscoderVersion;

- (NSString *)getMediaPlayerVersion;

- (NSString *)getMediaCoreVersion;

- (NSString *)getPSLStreamingVersion;

- (NSString *)getILiveBaseVersion;

@end

J2OBJC_EMPTY_STATIC_INIT(PILibraryVersionUtilApi)

J2OBJC_TYPE_LITERAL_HEADER(PILibraryVersionUtilApi)

#define ComPowerinfoPi_iroomApiLibraryVersionUtilApi PILibraryVersionUtilApi

#endif

#pragma pop_macro("INCLUDE_ALL_LibraryVersionUtilApi")
