//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/utils/NetworkChangeCallback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NetworkChangeCallback")
#ifdef RESTRICT_NetworkChangeCallback
#define INCLUDE_ALL_NetworkChangeCallback 0
#else
#define INCLUDE_ALL_NetworkChangeCallback 1
#endif
#undef RESTRICT_NetworkChangeCallback

#if !defined (PINetworkChangeCallback_) && (INCLUDE_ALL_NetworkChangeCallback || defined(INCLUDE_PINetworkChangeCallback))
#define PINetworkChangeCallback_

@protocol PINetworkChangeCallback < JavaObject >

- (void)onNetworkChange:(jint)type;

@end

J2OBJC_EMPTY_STATIC_INIT(PINetworkChangeCallback)

J2OBJC_TYPE_LITERAL_HEADER(PINetworkChangeCallback)

#define ComPowerinfoPi_iroomUtilsNetworkChangeCallback PINetworkChangeCallback

#endif

#pragma pop_macro("INCLUDE_ALL_NetworkChangeCallback")
