//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/api/PIiLiveBaseApi.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PIiLiveBaseApi")
#ifdef RESTRICT_PIiLiveBaseApi
#define INCLUDE_ALL_PIiLiveBaseApi 0
#else
#define INCLUDE_ALL_PIiLiveBaseApi 1
#endif
#undef RESTRICT_PIiLiveBaseApi

#if !defined (PIiLiveBaseApi_) && (INCLUDE_ALL_PIiLiveBaseApi || defined(INCLUDE_PIiLiveBaseApi))
#define PIiLiveBaseApi_

@protocol PIPsRefreshCallbackApi;
@protocol PIPsTimerCallbackApi;

@protocol PIiLiveBaseApi < JavaObject >

- (void)setForegroundStatus:(jint)status;

- (void)togglePzvtFrequency:(jint)freq;

- (NSString *)postRoomServer:(jint)ndSelect
                         url:(NSString *)url
                      header:(NSString *)requestHeader
                        body:(NSString *)requestBody
                   timeoutMs:(jint)timeoutMs;

- (jlong)getPzvt;

- (jint)psAddTask:(id<PIPsTimerCallbackApi>)callback
             pzvt:(jlong)pzvt
             data:(NSString *)data;

- (jint)psRemoveTask:(jint)id_;

- (void)refreshPzvt:(jint)force
           callback:(id<PIPsRefreshCallbackApi>)callback;

@end

J2OBJC_EMPTY_STATIC_INIT(PIiLiveBaseApi)

inline jint PIiLiveBaseApi_get_STATUS_BACKGROUND(void);
#define PIiLiveBaseApi_STATUS_BACKGROUND 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiLiveBaseApi, STATUS_BACKGROUND, jint)

inline jint PIiLiveBaseApi_get_STATUS_FOREGROUND(void);
#define PIiLiveBaseApi_STATUS_FOREGROUND 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiLiveBaseApi, STATUS_FOREGROUND, jint)

inline jint PIiLiveBaseApi_get_PZVT_FREQ_HIGH(void);
#define PIiLiveBaseApi_PZVT_FREQ_HIGH 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiLiveBaseApi, PZVT_FREQ_HIGH, jint)

inline jint PIiLiveBaseApi_get_PZVT_FREQ_LOW(void);
#define PIiLiveBaseApi_PZVT_FREQ_LOW 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiLiveBaseApi, PZVT_FREQ_LOW, jint)

inline jint PIiLiveBaseApi_get_PZVT_FREQ_STOP(void);
#define PIiLiveBaseApi_PZVT_FREQ_STOP 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiLiveBaseApi, PZVT_FREQ_STOP, jint)

J2OBJC_TYPE_LITERAL_HEADER(PIiLiveBaseApi)

#define ComPowerinfoPi_iroomApiPIiLiveBaseApi PIiLiveBaseApi

#endif

#pragma pop_macro("INCLUDE_ALL_PIiLiveBaseApi")
