//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/PIiRoomShared.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PIiRoomShared")
#ifdef RESTRICT_PIiRoomShared
#define INCLUDE_ALL_PIiRoomShared 0
#else
#define INCLUDE_ALL_PIiRoomShared 1
#endif
#undef RESTRICT_PIiRoomShared

#if !defined (PIiRoomShared_) && (INCLUDE_ALL_PIiRoomShared || defined(INCLUDE_PIiRoomShared))
#define PIiRoomShared_

@class PIRoomServer;

@interface PIiRoomShared : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)getGroupId;

+ (jint)getNdSelect;

+ (jint)getRsPort;

+ (void)getRxConfig:(NSString *)groupId
         roomServer:(PIRoomServer *)roomServer;

+ (jint)getRxFunctionBcInterval;

+ (jint)getRxRetry;

+ (jint)getRxTimeout;

+ (jboolean)isDebug;

+ (void)toggleDebugWithBoolean:(jboolean)debug;

@end

J2OBJC_EMPTY_STATIC_INIT(PIiRoomShared)

inline jint PIiRoomShared_get_CORE_STATUS_NET_RESULT(void);
#define PIiRoomShared_CORE_STATUS_NET_RESULT 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CORE_STATUS_NET_RESULT, jint)

inline jint PIiRoomShared_get_PZVT_UNAVAILABLE(void);
#define PIiRoomShared_PZVT_UNAVAILABLE 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PZVT_UNAVAILABLE, jint)

inline jint PIiRoomShared_get_PZVT_AVAILABLE(void);
#define PIiRoomShared_PZVT_AVAILABLE 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PZVT_AVAILABLE, jint)

inline jint PIiRoomShared_get_ERR_MIX_PZVT_ERROR_INITIATIVE(void);
#define PIiRoomShared_ERR_MIX_PZVT_ERROR_INITIATIVE 3001
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_MIX_PZVT_ERROR_INITIATIVE, jint)

inline jint PIiRoomShared_get_ERR_MIX_PZVT_ERROR_PASSIVITY(void);
#define PIiRoomShared_ERR_MIX_PZVT_ERROR_PASSIVITY 3002
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_MIX_PZVT_ERROR_PASSIVITY, jint)

inline jint PIiRoomShared_get_ERR_MIX_START_RS_ERROR(void);
#define PIiRoomShared_ERR_MIX_START_RS_ERROR 3003
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_MIX_START_RS_ERROR, jint)

inline jint PIiRoomShared_get_ERR_MIX_STOP_RS_ERROR(void);
#define PIiRoomShared_ERR_MIX_STOP_RS_ERROR 3004
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_MIX_STOP_RS_ERROR, jint)

inline jint PIiRoomShared_get_STATUS_FUNCTION_TYPE_PZVT_DELAY(void);
#define PIiRoomShared_STATUS_FUNCTION_TYPE_PZVT_DELAY 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STATUS_FUNCTION_TYPE_PZVT_DELAY, jint)

inline jint PIiRoomShared_get_MIX_TYPE_METRONOME(void);
#define PIiRoomShared_MIX_TYPE_METRONOME 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, MIX_TYPE_METRONOME, jint)

inline jint PIiRoomShared_get_MIX_TYPE_MUSIC(void);
#define PIiRoomShared_MIX_TYPE_MUSIC 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, MIX_TYPE_MUSIC, jint)

inline jint PIiRoomShared_get_MIX_TYPE_SYNC_METRONOME(void);
#define PIiRoomShared_MIX_TYPE_SYNC_METRONOME 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, MIX_TYPE_SYNC_METRONOME, jint)

inline jint PIiRoomShared_get_MIX_TYPE_SYNC_MUSIC(void);
#define PIiRoomShared_MIX_TYPE_SYNC_MUSIC 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, MIX_TYPE_SYNC_MUSIC, jint)

inline NSString *PIiRoomShared_get_SIG_MSG_SDK(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PIiRoomShared_SIG_MSG_SDK;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PIiRoomShared, SIG_MSG_SDK, NSString *)

inline NSString *PIiRoomShared_get_SIG_MSG_APP(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PIiRoomShared_SIG_MSG_APP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PIiRoomShared, SIG_MSG_APP, NSString *)

inline jint PIiRoomShared_get_CONNECTION_UNKNOWN(void);
#define PIiRoomShared_CONNECTION_UNKNOWN 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_UNKNOWN, jint)

inline jint PIiRoomShared_get_CONNECTION_ETHERNET(void);
#define PIiRoomShared_CONNECTION_ETHERNET 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_ETHERNET, jint)

inline jint PIiRoomShared_get_CONNECTION_WIFI(void);
#define PIiRoomShared_CONNECTION_WIFI 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_WIFI, jint)

inline jint PIiRoomShared_get_CONNECTION_4G(void);
#define PIiRoomShared_CONNECTION_4G 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_4G, jint)

inline jint PIiRoomShared_get_CONNECTION_3G(void);
#define PIiRoomShared_CONNECTION_3G 4
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_3G, jint)

inline jint PIiRoomShared_get_CONNECTION_2G(void);
#define PIiRoomShared_CONNECTION_2G 5
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_2G, jint)

inline jint PIiRoomShared_get_CONNECTION_UNKNOWN_CELLULAR(void);
#define PIiRoomShared_CONNECTION_UNKNOWN_CELLULAR 6
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_UNKNOWN_CELLULAR, jint)

inline jint PIiRoomShared_get_CONNECTION_BLUETOOTH(void);
#define PIiRoomShared_CONNECTION_BLUETOOTH 7
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_BLUETOOTH, jint)

inline jint PIiRoomShared_get_CONNECTION_NONE(void);
#define PIiRoomShared_CONNECTION_NONE 8
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, CONNECTION_NONE, jint)

inline jint PIiRoomShared_get_AEC_FORCE_OFF(void);
#define PIiRoomShared_AEC_FORCE_OFF 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AEC_FORCE_OFF, jint)

inline jint PIiRoomShared_get_AEC_FORCE_ON(void);
#define PIiRoomShared_AEC_FORCE_ON 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AEC_FORCE_ON, jint)

inline jint PIiRoomShared_get_AEC_AUTO(void);
#define PIiRoomShared_AEC_AUTO 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AEC_AUTO, jint)

inline jint PIiRoomShared_get_AEC_PREFER_ON(void);
#define PIiRoomShared_AEC_PREFER_ON 4
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AEC_PREFER_ON, jint)

inline jint PIiRoomShared_get_AEC_EARPHONE(void);
#define PIiRoomShared_AEC_EARPHONE 5
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AEC_EARPHONE, jint)

inline jint PIiRoomShared_get_REASON_LEAVE_ROOM(void);
#define PIiRoomShared_REASON_LEAVE_ROOM 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, REASON_LEAVE_ROOM, jint)

inline jint PIiRoomShared_get_REASON_KICK_OUT(void);
#define PIiRoomShared_REASON_KICK_OUT 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, REASON_KICK_OUT, jint)

inline jint PIiRoomShared_get_REASON_MAIN_VE_LEFT(void);
#define PIiRoomShared_REASON_MAIN_VE_LEFT 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, REASON_MAIN_VE_LEFT, jint)

inline jint PIiRoomShared_get_STOP_ACTION_STOP_STREAMING(void);
#define PIiRoomShared_STOP_ACTION_STOP_STREAMING 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STOP_ACTION_STOP_STREAMING, jint)

inline jint PIiRoomShared_get_STOP_ACTION_KEEP_AUDIO(void);
#define PIiRoomShared_STOP_ACTION_KEEP_AUDIO 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STOP_ACTION_KEEP_AUDIO, jint)

inline jint PIiRoomShared_get_STOP_ACTION_KEEP_ALL(void);
#define PIiRoomShared_STOP_ACTION_KEEP_ALL 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STOP_ACTION_KEEP_ALL, jint)

inline jint PIiRoomShared_get_SDK_PLAY_BOTH(void);
#define PIiRoomShared_SDK_PLAY_BOTH 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SDK_PLAY_BOTH, jint)

inline jint PIiRoomShared_get_SDK_PLAY_VIDEO_ONLY(void);
#define PIiRoomShared_SDK_PLAY_VIDEO_ONLY 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SDK_PLAY_VIDEO_ONLY, jint)

inline jint PIiRoomShared_get_SDK_PLAY_AUDIO_ONLY(void);
#define PIiRoomShared_SDK_PLAY_AUDIO_ONLY 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SDK_PLAY_AUDIO_ONLY, jint)

inline jint PIiRoomShared_get_SDK_PLAY_NONE(void);
#define PIiRoomShared_SDK_PLAY_NONE 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SDK_PLAY_NONE, jint)

inline jint PIiRoomShared_get_PROTO_MODE_PSP(void);
#define PIiRoomShared_PROTO_MODE_PSP 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PROTO_MODE_PSP, jint)

inline jint PIiRoomShared_get_PROTO_MODE_PDP_PROXY(void);
#define PIiRoomShared_PROTO_MODE_PDP_PROXY 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PROTO_MODE_PDP_PROXY, jint)

inline jint PIiRoomShared_get_PROTO_MODE_PDP_PURE(void);
#define PIiRoomShared_PROTO_MODE_PDP_PURE 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PROTO_MODE_PDP_PURE, jint)

inline jint PIiRoomShared_get_APP_SIG(void);
#define PIiRoomShared_APP_SIG 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, APP_SIG, jint)

inline jint PIiRoomShared_get_SDK_SIG(void);
#define PIiRoomShared_SDK_SIG 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SDK_SIG, jint)

inline jint PIiRoomShared_get_MIX_SIG(void);
#define PIiRoomShared_MIX_SIG 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, MIX_SIG, jint)

inline jint PIiRoomShared_get_STREAM_MODE_NONE(void);
#define PIiRoomShared_STREAM_MODE_NONE 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STREAM_MODE_NONE, jint)

inline jint PIiRoomShared_get_STREAM_MODE_ALL(void);
#define PIiRoomShared_STREAM_MODE_ALL 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STREAM_MODE_ALL, jint)

inline jint PIiRoomShared_get_STREAM_MODE_PARTIAL(void);
#define PIiRoomShared_STREAM_MODE_PARTIAL 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STREAM_MODE_PARTIAL, jint)

inline jint PIiRoomShared_get_STREAM_MODE_ONLY_ONE(void);
#define PIiRoomShared_STREAM_MODE_ONLY_ONE 4
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, STREAM_MODE_ONLY_ONE, jint)

inline jint PIiRoomShared_get_SCENE_PLAY_TYPE_NONE_ONE(void);
#define PIiRoomShared_SCENE_PLAY_TYPE_NONE_ONE 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SCENE_PLAY_TYPE_NONE_ONE, jint)

inline jint PIiRoomShared_get_SCENE_PLAY_TYPE_NONE_ALL(void);
#define PIiRoomShared_SCENE_PLAY_TYPE_NONE_ALL 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SCENE_PLAY_TYPE_NONE_ALL, jint)

inline jint PIiRoomShared_get_SCENE_PLAY_TYPE_ONE_ONE(void);
#define PIiRoomShared_SCENE_PLAY_TYPE_ONE_ONE 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SCENE_PLAY_TYPE_ONE_ONE, jint)

inline jint PIiRoomShared_get_SCENE_PLAY_TYPE_ONE_ALL(void);
#define PIiRoomShared_SCENE_PLAY_TYPE_ONE_ALL 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SCENE_PLAY_TYPE_ONE_ALL, jint)

inline jint PIiRoomShared_get_SCENE_PLAY_TYPE_ALL_ONE(void);
#define PIiRoomShared_SCENE_PLAY_TYPE_ALL_ONE 4
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SCENE_PLAY_TYPE_ALL_ONE, jint)

inline jint PIiRoomShared_get_SCENE_PLAY_TYPE_ALL_ALL(void);
#define PIiRoomShared_SCENE_PLAY_TYPE_ALL_ALL 5
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, SCENE_PLAY_TYPE_ALL_ALL, jint)

inline jint PIiRoomShared_get_FEATURE_DISABLE(void);
#define PIiRoomShared_FEATURE_DISABLE 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, FEATURE_DISABLE, jint)

inline jint PIiRoomShared_get_FEATURE_ENABLE(void);
#define PIiRoomShared_FEATURE_ENABLE 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, FEATURE_ENABLE, jint)

inline jint PIiRoomShared_get_PLAY_STREAM_MODE_MULTI_STREAM(void);
#define PIiRoomShared_PLAY_STREAM_MODE_MULTI_STREAM 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PLAY_STREAM_MODE_MULTI_STREAM, jint)

inline jint PIiRoomShared_get_PLAY_STREAM_MODE_LOW_DELAY(void);
#define PIiRoomShared_PLAY_STREAM_MODE_LOW_DELAY 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PLAY_STREAM_MODE_LOW_DELAY, jint)

inline jint PIiRoomShared_get_PLAY_STREAM_MODE_TRANS_SEG(void);
#define PIiRoomShared_PLAY_STREAM_MODE_TRANS_SEG 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PLAY_STREAM_MODE_TRANS_SEG, jint)

inline jint PIiRoomShared_get_PLAY_STREAM_MODE_MSC(void);
#define PIiRoomShared_PLAY_STREAM_MODE_MSC 4
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PLAY_STREAM_MODE_MSC, jint)

inline jint PIiRoomShared_get_PLAY_STREAM_MODE_EXTERNAL_CDN(void);
#define PIiRoomShared_PLAY_STREAM_MODE_EXTERNAL_CDN 5
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, PLAY_STREAM_MODE_EXTERNAL_CDN, jint)

inline jint PIiRoomShared_get_ROLE_NORMAL(void);
#define PIiRoomShared_ROLE_NORMAL 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ROLE_NORMAL, jint)

inline jint PIiRoomShared_get_ROLE_VIEWER(void);
#define PIiRoomShared_ROLE_VIEWER 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ROLE_VIEWER, jint)

inline jint PIiRoomShared_get_ROLE_FLEX(void);
#define PIiRoomShared_ROLE_FLEX 4
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ROLE_FLEX, jint)

inline jint PIiRoomShared_get_LEAVE_ORIGIN_BEHAVIOR_LEAVE_ALL(void);
#define PIiRoomShared_LEAVE_ORIGIN_BEHAVIOR_LEAVE_ALL 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, LEAVE_ORIGIN_BEHAVIOR_LEAVE_ALL, jint)

inline jint PIiRoomShared_get_LEAVE_ORIGIN_BEHAVIOR_ALLOC_NEW_SLOT(void);
#define PIiRoomShared_LEAVE_ORIGIN_BEHAVIOR_ALLOC_NEW_SLOT 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, LEAVE_ORIGIN_BEHAVIOR_ALLOC_NEW_SLOT, jint)

inline jint PIiRoomShared_get_TARGETS_FILTER_MODE_ACCEPT(void);
#define PIiRoomShared_TARGETS_FILTER_MODE_ACCEPT 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, TARGETS_FILTER_MODE_ACCEPT, jint)

inline jint PIiRoomShared_get_TARGETS_FILTER_MODE_REJECT(void);
#define PIiRoomShared_TARGETS_FILTER_MODE_REJECT 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, TARGETS_FILTER_MODE_REJECT, jint)

inline jint PIiRoomShared_get_AX_A200(void);
#define PIiRoomShared_AX_A200 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AX_A200, jint)

inline jint PIiRoomShared_get_AX_ADL_BASE(void);
#define PIiRoomShared_AX_ADL_BASE 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AX_ADL_BASE, jint)

inline jint PIiRoomShared_get_AX_A50_BASE(void);
#define PIiRoomShared_AX_A50_BASE 3
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AX_A50_BASE, jint)

inline jint PIiRoomShared_get_AX_A40_BASE(void);
#define PIiRoomShared_AX_A40_BASE 4
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, AX_A40_BASE, jint)

inline jint PIiRoomShared_get_A50_STATE_DISABLE(void);
#define PIiRoomShared_A50_STATE_DISABLE 100
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, A50_STATE_DISABLE, jint)

inline jint PIiRoomShared_get_A50_STATE_A1(void);
#define PIiRoomShared_A50_STATE_A1 300
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, A50_STATE_A1, jint)

inline jint PIiRoomShared_get_A50_STATE_A2(void);
#define PIiRoomShared_A50_STATE_A2 400
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, A50_STATE_A2, jint)

inline jint PIiRoomShared_get_A50_STATE_A3(void);
#define PIiRoomShared_A50_STATE_A3 500
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, A50_STATE_A3, jint)

inline jint PIiRoomShared_get_A50_STATE_A4(void);
#define PIiRoomShared_A50_STATE_A4 600
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, A50_STATE_A4, jint)

inline jint PIiRoomShared_get_LAYOUT_TYPE_SDK(void);
#define PIiRoomShared_LAYOUT_TYPE_SDK 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, LAYOUT_TYPE_SDK, jint)

inline jint PIiRoomShared_get_LAYOUT_TYPE_APP(void);
#define PIiRoomShared_LAYOUT_TYPE_APP 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, LAYOUT_TYPE_APP, jint)

inline jint PIiRoomShared_get_NETWORK_DEVICE_MOBILE(void);
#define PIiRoomShared_NETWORK_DEVICE_MOBILE 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, NETWORK_DEVICE_MOBILE, jint)

inline jint PIiRoomShared_get_NETWORK_DEVICE_WIFI(void);
#define PIiRoomShared_NETWORK_DEVICE_WIFI 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, NETWORK_DEVICE_WIFI, jint)

inline jint PIiRoomShared_get_RS_RESULT_SUCCESS(void);
#define PIiRoomShared_RS_RESULT_SUCCESS 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_SUCCESS, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_INVALID_ROOM_ID(void);
#define PIiRoomShared_RS_RESULT_ERROR_INVALID_ROOM_ID 1001
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_INVALID_ROOM_ID, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_INVALID_UID(void);
#define PIiRoomShared_RS_RESULT_ERROR_INVALID_UID 1002
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_INVALID_UID, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_OPERATION_NOT_ALLOWED(void);
#define PIiRoomShared_RS_RESULT_ERROR_OPERATION_NOT_ALLOWED 1009
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_OPERATION_NOT_ALLOWED, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_OPERATION_FAIL(void);
#define PIiRoomShared_RS_RESULT_ERROR_OPERATION_FAIL 1010
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_OPERATION_FAIL, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_JOIN_NOT_EXIST_ROOM(void);
#define PIiRoomShared_RS_RESULT_ERROR_JOIN_NOT_EXIST_ROOM 1101
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_JOIN_NOT_EXIST_ROOM, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_LEAVE_NOT_EXIST_ROOM(void);
#define PIiRoomShared_RS_RESULT_ERROR_LEAVE_NOT_EXIST_ROOM 1102
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_LEAVE_NOT_EXIST_ROOM, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_LEAVE_NOT_JOINED_ROOM(void);
#define PIiRoomShared_RS_RESULT_ERROR_LEAVE_NOT_JOINED_ROOM 1103
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_LEAVE_NOT_JOINED_ROOM, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_JOIN_FULL_ROOMS(void);
#define PIiRoomShared_RS_RESULT_ERROR_JOIN_FULL_ROOMS 1104
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_JOIN_FULL_ROOMS, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_LEAVE_ORIGIN_ALLOC_NEW_FAIL(void);
#define PIiRoomShared_RS_RESULT_ERROR_LEAVE_ORIGIN_ALLOC_NEW_FAIL 1105
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_LEAVE_ORIGIN_ALLOC_NEW_FAIL, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_INTERNAL_DATA_INCONSISTENT(void);
#define PIiRoomShared_RS_RESULT_ERROR_INTERNAL_DATA_INCONSISTENT 1106
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_INTERNAL_DATA_INCONSISTENT, jint)

inline jint PIiRoomShared_get_RS_RESULT_ERROR_BOTH_MERGE_SPLIT_INFO_PRESENT(void);
#define PIiRoomShared_RS_RESULT_ERROR_BOTH_MERGE_SPLIT_INFO_PRESENT 1107
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, RS_RESULT_ERROR_BOTH_MERGE_SPLIT_INFO_PRESENT, jint)

inline jint PIiRoomShared_get_ERR_FEATURE_GROUP_CHAT(void);
#define PIiRoomShared_ERR_FEATURE_GROUP_CHAT 2000
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_FEATURE_GROUP_CHAT, jint)

inline jint PIiRoomShared_get_ERR_INVALID_MESSAGE(void);
#define PIiRoomShared_ERR_INVALID_MESSAGE 2004
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_INVALID_MESSAGE, jint)

inline jint PIiRoomShared_get_ERR_RS_CHANGE_ROLE(void);
#define PIiRoomShared_ERR_RS_CHANGE_ROLE 2009
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_RS_CHANGE_ROLE, jint)

inline jint PIiRoomShared_get_ERR_HB_TIMEOUT(void);
#define PIiRoomShared_ERR_HB_TIMEOUT 2010
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_HB_TIMEOUT, jint)

inline jint PIiRoomShared_get_ERR_PUSH_TIMEOUT(void);
#define PIiRoomShared_ERR_PUSH_TIMEOUT 2011
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_PUSH_TIMEOUT, jint)

inline jint PIiRoomShared_get_ERR_BACKGROUND_TIMEOUT(void);
#define PIiRoomShared_ERR_BACKGROUND_TIMEOUT 2012
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_BACKGROUND_TIMEOUT, jint)

inline jint PIiRoomShared_get_ERR_INVALID_PLAY_TARGET(void);
#define PIiRoomShared_ERR_INVALID_PLAY_TARGET 2013
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_INVALID_PLAY_TARGET, jint)

inline jint PIiRoomShared_get_ERR_WINDOW_DUPLICATE_ZINDEX(void);
#define PIiRoomShared_ERR_WINDOW_DUPLICATE_ZINDEX 2018
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_WINDOW_DUPLICATE_ZINDEX, jint)

inline jint PIiRoomShared_get_ERR_MULTIPLE_FULLSCREEN_WINDOW(void);
#define PIiRoomShared_ERR_MULTIPLE_FULLSCREEN_WINDOW 2019
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_MULTIPLE_FULLSCREEN_WINDOW, jint)

inline jint PIiRoomShared_get_ERR_FULLSCREEN_WINDOW_WITH_WRONG_ZINDEX(void);
#define PIiRoomShared_ERR_FULLSCREEN_WINDOW_WITH_WRONG_ZINDEX 2020
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_FULLSCREEN_WINDOW_WITH_WRONG_ZINDEX, jint)

inline jint PIiRoomShared_get_ERR_USERWINDOW_AND_VIEW_MISMATCH(void);
#define PIiRoomShared_ERR_USERWINDOW_AND_VIEW_MISMATCH 2021
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_USERWINDOW_AND_VIEW_MISMATCH, jint)

inline jint PIiRoomShared_get_ERR_ALLOC_WINDOW_FAIL(void);
#define PIiRoomShared_ERR_ALLOC_WINDOW_FAIL 2022
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_ALLOC_WINDOW_FAIL, jint)

inline jint PIiRoomShared_get_ERR_TRANSCODER_FATAL(void);
#define PIiRoomShared_ERR_TRANSCODER_FATAL 2023
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_TRANSCODER_FATAL, jint)

inline jint PIiRoomShared_get_ERR_SIG_CONNECT_FAIL(void);
#define PIiRoomShared_ERR_SIG_CONNECT_FAIL 2024
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_SIG_CONNECT_FAIL, jint)

inline jint PIiRoomShared_get_ERR_EMPTY_SIG_URL(void);
#define PIiRoomShared_ERR_EMPTY_SIG_URL 2025
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_EMPTY_SIG_URL, jint)

inline jint PIiRoomShared_get_ERR_DISCONNECTED(void);
#define PIiRoomShared_ERR_DISCONNECTED 2026
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_DISCONNECTED, jint)

inline jint PIiRoomShared_get_ERR_INVALID_LAYOUT_CONFIG(void);
#define PIiRoomShared_ERR_INVALID_LAYOUT_CONFIG 2029
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_INVALID_LAYOUT_CONFIG, jint)

inline jint PIiRoomShared_get_ERR_MULTIPLE_PEER(void);
#define PIiRoomShared_ERR_MULTIPLE_PEER 2030
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_MULTIPLE_PEER, jint)

inline jint PIiRoomShared_get_ERR_RESOURCE_BUSY(void);
#define PIiRoomShared_ERR_RESOURCE_BUSY 2031
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_RESOURCE_BUSY, jint)

inline jint PIiRoomShared_get_ERR_WRONG_NAME(void);
#define PIiRoomShared_ERR_WRONG_NAME 2040
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_WRONG_NAME, jint)

inline jint PIiRoomShared_get_ERR_PZVT_REFRESH(void);
#define PIiRoomShared_ERR_PZVT_REFRESH 2050
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_PZVT_REFRESH, jint)

inline jint PIiRoomShared_get_ERR_REPORT_CAP_TIMEOUT(void);
#define PIiRoomShared_ERR_REPORT_CAP_TIMEOUT 2051
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_REPORT_CAP_TIMEOUT, jint)

inline jint PIiRoomShared_get_ERR_IJK_ERR_AUDIODEV(void);
#define PIiRoomShared_ERR_IJK_ERR_AUDIODEV 3001
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_IJK_ERR_AUDIODEV, jint)

inline jint PIiRoomShared_get_ERR_RS_API_TIMEOUT(void);
#define PIiRoomShared_ERR_RS_API_TIMEOUT 10000
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_RS_API_TIMEOUT, jint)

inline jint PIiRoomShared_get_ERR_RS_UNKNOWN(void);
#define PIiRoomShared_ERR_RS_UNKNOWN 10001
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, ERR_RS_UNKNOWN, jint)

inline jint PIiRoomShared_get_DEFAULT_RS_TIMEOUT_THRESHOLD(void);
#define PIiRoomShared_DEFAULT_RS_TIMEOUT_THRESHOLD 5000
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, DEFAULT_RS_TIMEOUT_THRESHOLD, jint)

inline jint PIiRoomShared_get_DEFAULT_ROOM_SIZE(void);
#define PIiRoomShared_DEFAULT_ROOM_SIZE 9
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomShared, DEFAULT_ROOM_SIZE, jint)

inline NSString *PIiRoomShared_get_TAG(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PIiRoomShared_TAG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PIiRoomShared, TAG, NSString *)

inline jint PIiRoomShared_get_sRxTimeout(void);
inline jint PIiRoomShared_set_sRxTimeout(jint value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT volatile_jint PIiRoomShared_sRxTimeout;
J2OBJC_STATIC_FIELD_PRIMITIVE_VOLATILE(PIiRoomShared, sRxTimeout, jint)

inline jint PIiRoomShared_get_sRxRetry(void);
inline jint PIiRoomShared_set_sRxRetry(jint value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT volatile_jint PIiRoomShared_sRxRetry;
J2OBJC_STATIC_FIELD_PRIMITIVE_VOLATILE(PIiRoomShared, sRxRetry, jint)

inline jint PIiRoomShared_get_sRxFunctionBcInterval(void);
inline jint PIiRoomShared_set_sRxFunctionBcInterval(jint value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT volatile_jint PIiRoomShared_sRxFunctionBcInterval;
J2OBJC_STATIC_FIELD_PRIMITIVE_VOLATILE(PIiRoomShared, sRxFunctionBcInterval, jint)

inline NSString *PIiRoomShared_get_sGroupId(void);
inline NSString *PIiRoomShared_set_sGroupId(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PIiRoomShared_sGroupId;
J2OBJC_STATIC_FIELD_OBJ(PIiRoomShared, sGroupId, NSString *)

inline jint PIiRoomShared_get_sNdSelect(void);
inline jint PIiRoomShared_set_sNdSelect(jint value);
inline jint *PIiRoomShared_getRef_sNdSelect(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint PIiRoomShared_sNdSelect;
J2OBJC_STATIC_FIELD_PRIMITIVE(PIiRoomShared, sNdSelect, jint)

inline jint PIiRoomShared_get_sRsPort(void);
inline jint PIiRoomShared_set_sRsPort(jint value);
inline jint *PIiRoomShared_getRef_sRsPort(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint PIiRoomShared_sRsPort;
J2OBJC_STATIC_FIELD_PRIMITIVE(PIiRoomShared, sRsPort, jint)

FOUNDATION_EXPORT void PIiRoomShared_init(PIiRoomShared *self);

FOUNDATION_EXPORT PIiRoomShared *new_PIiRoomShared_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIiRoomShared *create_PIiRoomShared_init(void);

FOUNDATION_EXPORT void PIiRoomShared_toggleDebugWithBoolean_(jboolean debug);

FOUNDATION_EXPORT jboolean PIiRoomShared_isDebug(void);

FOUNDATION_EXPORT NSString *PIiRoomShared_getGroupId(void);

FOUNDATION_EXPORT jint PIiRoomShared_getNdSelect(void);

FOUNDATION_EXPORT jint PIiRoomShared_getRsPort(void);

FOUNDATION_EXPORT jint PIiRoomShared_getRxTimeout(void);

FOUNDATION_EXPORT jint PIiRoomShared_getRxRetry(void);

FOUNDATION_EXPORT jint PIiRoomShared_getRxFunctionBcInterval(void);

FOUNDATION_EXPORT void PIiRoomShared_getRxConfig_roomServer_(NSString *groupId, PIRoomServer *roomServer);

J2OBJC_TYPE_LITERAL_HEADER(PIiRoomShared)

@compatibility_alias ComPowerinfoPi_iroomPIiRoomShared PIiRoomShared;

#endif

#if !defined (PIiRoomShared_PeerCallback_) && (INCLUDE_ALL_PIiRoomShared || defined(INCLUDE_PIiRoomShared_PeerCallback))
#define PIiRoomShared_PeerCallback_

@class PIAudioDevice;
@protocol JavaUtilMap;

@protocol PIiRoomShared_PeerCallback < JavaObject >

- (void)onReceivePeerVideoSuccess2:(NSString *)roomId
                            andUid:(NSString *)uid;

- (void)onReceivePeerAudioSuccess2:(NSString *)roomId
                            andUid:(NSString *)uid;

- (void)onPeerLeft2:(NSString *)roomId
             andUid:(NSString *)uid;

- (void)onKickout:(NSString *)roomId;

- (void)onMainVeLeft:(NSString *)roomId;

- (void)onPeerVeJoined:(NSString *)roomId
                andUid:(NSString *)uid
             andVeName:(NSString *)veName;

- (void)onPeerVeLeft:(NSString *)roomId
              andUid:(NSString *)uid
           andVeName:(NSString *)veName;

- (void)onLeftiRoom2:(NSString *)roomId;

- (void)onJoinediRoom2:(NSString *)roomId;

- (void)onLeftAlliRoom;

- (void)onMessageOutput3:(NSString *)roomId
          withReceiveUid:(NSString *)receiverUid
      withReceiverVeName:(NSString *)veName
             withMessage:(NSString *)message;

- (void)onRsSuccess:(NSString *)rsReqId;

- (void)onError:(jint)code
        andData:(NSString *)data;

- (void)onAecStatusChanged:(jboolean)enabled;

- (void)onAudioDeviceChanged:(PIAudioDevice *)audioDevice;

- (void)oniRoomDestroyed2:(NSString *)roomId;

- (void)onTranscoderCreated;

- (void)onReceiveAppPrivateData:(NSString *)data;

- (void)onPsTimerFired:(NSString *)data;

- (void)onReceiveAppMessageWithRid:(NSString *)rid
                       withFromUid:(NSString *)fromUid
                    withFromVeName:(NSString *)fromVeName
                          withData:(NSString *)data;

- (void)onChangeVeName:(NSString *)roomId
               withUid:(NSString *)uid
         withOldVeName:(NSString *)oldVeName
         withNewVeName:(NSString *)newVeName;

- (void)onVeNameChanged:(NSString *)roomId
                withUid:(NSString *)uid
          withOldVeName:(NSString *)oldVeName
          withNewVeName:(NSString *)newVeName;

- (void)onSelfAxModeChanged:(jint)axMode;

- (void)onRoomAxModeChanged:(jint)axMode;

- (void)onReceiveEventFromPusher:(NSString *)roomId
                          andUid:(NSString *)uid
                 andEventContent:(NSString *)eventContent;

- (void)onReceiveEventFromPlayer:(NSString *)data;

- (void)onChangeExternalState:(NSString *)data;

- (void)onChangeSelfExternalState:(NSString *)data;

- (void)onPushStreamingSuccess:(NSString *)roomId
                        andUid:(NSString *)uid;

- (void)onUserCapResult:(id<JavaUtilMap>)result;

- (void)onNetStatusResult:(NSString *)uid
                andVeName:(NSString *)veName
               andContent:(NSString *)content;

- (void)onA50StateChange:(jint)a50State;

- (void)onA50StateChangeSuccess:(jint)a50State;

- (void)onReceivePeerVideoSuccess:(jlong)roomId
                           andUid:(NSString *)uid;

- (void)onReceivePeerAudioSuccess:(jlong)roomId
                           andUid:(NSString *)uid;

- (void)onIAEvent:(jlong)roomId
           andUid:(NSString *)uid
  andEventContent:(NSString *)eventContent;

- (void)onPeerLeft:(jlong)roomId
            andUid:(NSString *)uid;

- (void)onLeftiRoom:(jlong)roomId;

- (void)onJoinediRoom:(jlong)roomId;

- (void)onMessageOutput:(jlong)roomId
         withReceiveUid:(NSString *)receiverUid
            withMessage:(NSString *)message;

- (void)onMessageOutput2:(NSString *)roomId
          withReceiveUid:(NSString *)receiverUid
             withMessage:(NSString *)message;

- (void)oniRoomDestroyed:(jlong)roomId;

- (void)onIAEvent2:(NSString *)roomId
            andUid:(NSString *)uid
   andEventContent:(NSString *)eventContent;

@end

J2OBJC_EMPTY_STATIC_INIT(PIiRoomShared_PeerCallback)

J2OBJC_TYPE_LITERAL_HEADER(PIiRoomShared_PeerCallback)

#endif

#if !defined (PIMixerCallback_) && (INCLUDE_ALL_PIiRoomShared || defined(INCLUDE_PIMixerCallback))
#define PIMixerCallback_

@protocol PIMixerCallback < JavaObject >

- (void)onMixerMusicStart;

- (void)onProgressChanged:(jlong)progress
          progressPercent:(jfloat)progressPercent;

- (void)onMixerMusicFinished:(jint)ssrc;

- (void)onMixerMusicError:(jint)ssrc
                     code:(jint)code;

- (void)onMetronomeStopped;

@end

J2OBJC_EMPTY_STATIC_INIT(PIMixerCallback)

J2OBJC_TYPE_LITERAL_HEADER(PIMixerCallback)

#endif

#if !defined (PIiRoomShared_Config_) && (INCLUDE_ALL_PIiRoomShared || defined(INCLUDE_PIiRoomShared_Config))
#define PIiRoomShared_Config_

#define RESTRICT_RoomConfig 1
#define INCLUDE_PIRoomConfig 1
#include "RoomConfig.h"

@class PIPlayerExtraOptions;
@class PIiRoomShared_Config_Builder;

@interface PIiRoomShared_Config : PIRoomConfig

#pragma mark Public

- (jint)aecMode;

- (jint)backgroundBehavior;

+ (PIiRoomShared_Config_Builder *)builder;

- (jboolean)disableAudioManager;

- (jboolean)enableA50Support;

- (jboolean)enableDetectSpeakerAndVolume;

- (jboolean)enableVePlaySync;

- (NSString *)encUrlParamsOverride;

- (id)ijkExtraOptions;

- (NSString *)linkUrlParamsOverride;

- (jint)onlyPlayAVAudioSessionOption;

- (jint)onlyPushAVAudioSessionOption;

- (jint)onlyPushIFrameInterval;

- (jint)pushAndPlayAVAudioSessionOption;

- (jint)pushAndPlayIFrameInterval;

- (jint)pushDelayThreshold;

- (jint)pushFailTimeout;

- (NSString *)pushUrlParamsOverride;

- (jboolean)pushVideo;

- (jboolean)reportWarning;

- (jint)sdkPlayMode;

- (jint)sigMode;

- (jboolean)stopPlayOnPause;

#pragma mark Package-Private

- (instancetype)initWithSigMode:(jint)sigMode
                      pushVideo:(jboolean)pushVideo
                    sdkPlayMode:(jint)sdkPlayMode
             backgroundBehavior:(jint)backgroundBehavior
             pushDelayThreshold:(jint)pushDelayThreshold
                pushFailTimeout:(jint)pushFailTimeout
      pushAndPlayIFrameInterval:(jint)pushAndPlayIFrameInterval
         onlyPushIFrameInterval:(jint)onlyPushIFrameInterval
pushAndPlayAVAudioSessionOption:(jint)pushAndPlayAVAudioSessionOption
   onlyPushAVAudioSessionOption:(jint)onlyPushAVAudioSessionOption
   onlyPlayAVAudioSessionOption:(jint)onlyPlayAVAudioSessionOption
                stopPlayOnPause:(jboolean)stopPlayOnPause
            disableAudioManager:(jboolean)disableAudioManager
               enableA50Support:(jboolean)enableA50Support
   enableDetectSpeakerAndVolume:(jboolean)enableDetectSpeakerAndVolume
       reportNoneFatalRsTimeout:(jboolean)reportNoneFatalRsTimeout
                  reportWarning:(jboolean)reportWarning
                        aecMode:(jint)aecMode
               enableVePlaySync:(jboolean)enableVePlaySync
          pushUrlParamsOverride:(NSString *)pushUrlParamsOverride
          linkUrlParamsOverride:(NSString *)linkUrlParamsOverride
           encUrlParamsOverride:(NSString *)encUrlParamsOverride
             playerExtraOptions:(PIPlayerExtraOptions *)playerExtraOptions;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithInt:(jint)arg0
                withBoolean:(jboolean)arg1
                    withInt:(jint)arg2
                    withInt:(jint)arg3
                    withInt:(jint)arg4
                    withInt:(jint)arg5
                    withInt:(jint)arg6
                    withInt:(jint)arg7
                    withInt:(jint)arg8
                    withInt:(jint)arg9
                    withInt:(jint)arg10
                withBoolean:(jboolean)arg11
                withBoolean:(jboolean)arg12
                withBoolean:(jboolean)arg13
                withBoolean:(jboolean)arg14
                withBoolean:(jboolean)arg15
                withBoolean:(jboolean)arg16
                    withInt:(jint)arg17
                withBoolean:(jboolean)arg18
               withNSString:(NSString *)arg19
               withNSString:(NSString *)arg20
               withNSString:(NSString *)arg21
   withPIPlayerExtraOptions:(PIPlayerExtraOptions *)arg22 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIiRoomShared_Config)

FOUNDATION_EXPORT void PIiRoomShared_Config_initWithSigMode_pushVideo_sdkPlayMode_backgroundBehavior_pushDelayThreshold_pushFailTimeout_pushAndPlayIFrameInterval_onlyPushIFrameInterval_pushAndPlayAVAudioSessionOption_onlyPushAVAudioSessionOption_onlyPlayAVAudioSessionOption_stopPlayOnPause_disableAudioManager_enableA50Support_enableDetectSpeakerAndVolume_reportNoneFatalRsTimeout_reportWarning_aecMode_enableVePlaySync_pushUrlParamsOverride_linkUrlParamsOverride_encUrlParamsOverride_playerExtraOptions_(PIiRoomShared_Config *self, jint sigMode, jboolean pushVideo, jint sdkPlayMode, jint backgroundBehavior, jint pushDelayThreshold, jint pushFailTimeout, jint pushAndPlayIFrameInterval, jint onlyPushIFrameInterval, jint pushAndPlayAVAudioSessionOption, jint onlyPushAVAudioSessionOption, jint onlyPlayAVAudioSessionOption, jboolean stopPlayOnPause, jboolean disableAudioManager, jboolean enableA50Support, jboolean enableDetectSpeakerAndVolume, jboolean reportNoneFatalRsTimeout, jboolean reportWarning, jint aecMode, jboolean enableVePlaySync, NSString *pushUrlParamsOverride, NSString *linkUrlParamsOverride, NSString *encUrlParamsOverride, PIPlayerExtraOptions *playerExtraOptions);

FOUNDATION_EXPORT PIiRoomShared_Config *new_PIiRoomShared_Config_initWithSigMode_pushVideo_sdkPlayMode_backgroundBehavior_pushDelayThreshold_pushFailTimeout_pushAndPlayIFrameInterval_onlyPushIFrameInterval_pushAndPlayAVAudioSessionOption_onlyPushAVAudioSessionOption_onlyPlayAVAudioSessionOption_stopPlayOnPause_disableAudioManager_enableA50Support_enableDetectSpeakerAndVolume_reportNoneFatalRsTimeout_reportWarning_aecMode_enableVePlaySync_pushUrlParamsOverride_linkUrlParamsOverride_encUrlParamsOverride_playerExtraOptions_(jint sigMode, jboolean pushVideo, jint sdkPlayMode, jint backgroundBehavior, jint pushDelayThreshold, jint pushFailTimeout, jint pushAndPlayIFrameInterval, jint onlyPushIFrameInterval, jint pushAndPlayAVAudioSessionOption, jint onlyPushAVAudioSessionOption, jint onlyPlayAVAudioSessionOption, jboolean stopPlayOnPause, jboolean disableAudioManager, jboolean enableA50Support, jboolean enableDetectSpeakerAndVolume, jboolean reportNoneFatalRsTimeout, jboolean reportWarning, jint aecMode, jboolean enableVePlaySync, NSString *pushUrlParamsOverride, NSString *linkUrlParamsOverride, NSString *encUrlParamsOverride, PIPlayerExtraOptions *playerExtraOptions) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIiRoomShared_Config *create_PIiRoomShared_Config_initWithSigMode_pushVideo_sdkPlayMode_backgroundBehavior_pushDelayThreshold_pushFailTimeout_pushAndPlayIFrameInterval_onlyPushIFrameInterval_pushAndPlayAVAudioSessionOption_onlyPushAVAudioSessionOption_onlyPlayAVAudioSessionOption_stopPlayOnPause_disableAudioManager_enableA50Support_enableDetectSpeakerAndVolume_reportNoneFatalRsTimeout_reportWarning_aecMode_enableVePlaySync_pushUrlParamsOverride_linkUrlParamsOverride_encUrlParamsOverride_playerExtraOptions_(jint sigMode, jboolean pushVideo, jint sdkPlayMode, jint backgroundBehavior, jint pushDelayThreshold, jint pushFailTimeout, jint pushAndPlayIFrameInterval, jint onlyPushIFrameInterval, jint pushAndPlayAVAudioSessionOption, jint onlyPushAVAudioSessionOption, jint onlyPlayAVAudioSessionOption, jboolean stopPlayOnPause, jboolean disableAudioManager, jboolean enableA50Support, jboolean enableDetectSpeakerAndVolume, jboolean reportNoneFatalRsTimeout, jboolean reportWarning, jint aecMode, jboolean enableVePlaySync, NSString *pushUrlParamsOverride, NSString *linkUrlParamsOverride, NSString *encUrlParamsOverride, PIPlayerExtraOptions *playerExtraOptions);

FOUNDATION_EXPORT PIiRoomShared_Config_Builder *PIiRoomShared_Config_builder(void);

J2OBJC_TYPE_LITERAL_HEADER(PIiRoomShared_Config)

#endif

#if !defined (PIiRoomShared_Config_Builder_) && (INCLUDE_ALL_PIiRoomShared || defined(INCLUDE_PIiRoomShared_Config_Builder))
#define PIiRoomShared_Config_Builder_

@class PIPlayerExtraOptions;
@class PIiRoomShared_Config;

@interface PIiRoomShared_Config_Builder : NSObject

#pragma mark Public

- (PIiRoomShared_Config_Builder *)aecModeWithInt:(jint)aecMode;

- (PIiRoomShared_Config_Builder *)backgroundBehaviorWithInt:(jint)backgroundBehavior;

- (PIiRoomShared_Config *)build;

- (PIiRoomShared_Config_Builder *)disableAudioManagerWithBoolean:(jboolean)disableAudioManager;

- (PIiRoomShared_Config_Builder *)enableA50SupportWithBoolean:(jboolean)enableA50Support;

- (PIiRoomShared_Config_Builder *)enableDetectSpeakerAndVolumeWithBoolean:(jboolean)enableDetectSpeakerAndVolume;

- (PIiRoomShared_Config_Builder *)enableVePlaySyncWithBoolean:(jboolean)enableVePlaySync;

- (PIiRoomShared_Config_Builder *)encUrlParamsOverrideWithNSString:(NSString *)encUrlParamsOverride;

- (PIiRoomShared_Config_Builder *)ijkExtraOptionsWithPIPlayerExtraOptions:(PIPlayerExtraOptions *)ijkExtraOptions;

- (PIiRoomShared_Config_Builder *)linkUrlParamsOverrideWithNSString:(NSString *)linkUrlParamsOverride;

- (PIiRoomShared_Config_Builder *)onlyPlayAVAudioSessionOptionWithInt:(jint)onlyPlayAVAudioSessionOption;

- (PIiRoomShared_Config_Builder *)onlyPushAVAudioSessionOptionWithInt:(jint)onlyPushAVAudioSessionOption;

- (PIiRoomShared_Config_Builder *)onlyPushIFrameIntervalWithInt:(jint)onlyPushIFrameInterval;

- (PIiRoomShared_Config_Builder *)pushAndPlayAVAudioSessionOptionWithInt:(jint)pushAndPlayAVAudioSessionOption;

- (PIiRoomShared_Config_Builder *)pushAndPlayIFrameIntervalWithInt:(jint)pushAndPlayIFrameInterval;

- (PIiRoomShared_Config_Builder *)pushDelayThresholdWithInt:(jint)pushDelayThreshold;

- (PIiRoomShared_Config_Builder *)pushFailTimeoutWithInt:(jint)pushFailTimeout;

- (PIiRoomShared_Config_Builder *)pushUrlParamsOverrideWithNSString:(NSString *)pushUrlParamsOverride;

- (PIiRoomShared_Config_Builder *)pushVideoWithBoolean:(jboolean)pushVideo;

- (PIiRoomShared_Config_Builder *)reportNoneFatalRsTimeoutWithBoolean:(jboolean)reportNoneFatalRsTimeout;

- (PIiRoomShared_Config_Builder *)reportWarningWithBoolean:(jboolean)reportWarning;

- (PIiRoomShared_Config_Builder *)sdkPlayModeWithInt:(jint)sdkPlayMode;

- (PIiRoomShared_Config_Builder *)sigModeWithInt:(jint)sigMode;

- (PIiRoomShared_Config_Builder *)stopPlayOnPauseWithBoolean:(jboolean)stopPlayOnPause;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(PIiRoomShared_Config_Builder)

FOUNDATION_EXPORT void PIiRoomShared_Config_Builder_init(PIiRoomShared_Config_Builder *self);

FOUNDATION_EXPORT PIiRoomShared_Config_Builder *new_PIiRoomShared_Config_Builder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIiRoomShared_Config_Builder *create_PIiRoomShared_Config_Builder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(PIiRoomShared_Config_Builder)

#endif

#pragma pop_macro("INCLUDE_ALL_PIiRoomShared")
