//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/core/PIiRoomMessage.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PIiRoomMessage")
#ifdef RESTRICT_PIiRoomMessage
#define INCLUDE_ALL_PIiRoomMessage 0
#else
#define INCLUDE_ALL_PIiRoomMessage 1
#endif
#undef RESTRICT_PIiRoomMessage

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIiRoomMessage_) && (INCLUDE_ALL_PIiRoomMessage || defined(INCLUDE_PIiRoomMessage))
#define PIiRoomMessage_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;
@protocol JavaUtilList;

@interface PIiRoomMessage : NSObject

#pragma mark Public

- (instancetype)init;

+ (PIiRoomMessage *)createWithLong:(jlong)seq
                          withLong:(jlong)room_id
                           withInt:(jint)type
                      withNSString:(NSString *)uid
                      withNSString:(NSString *)ve_name
                  withJavaUtilList:(id<JavaUtilList>)push_targets
                  withJavaUtilList:(id<JavaUtilList>)play_targets
                  withJavaUtilList:(id<JavaUtilList>)us_acts;

+ (PIiRoomMessage *)create2WithLong:(jlong)seq
                            withInt:(jint)reason
                           withLong:(jlong)room_id
                       withNSString:(NSString *)sroom_id
                            withInt:(jint)type
                       withNSString:(NSString *)uid
                       withNSString:(NSString *)ve_name
                   withJavaUtilList:(id<JavaUtilList>)push_targets
                   withJavaUtilList:(id<JavaUtilList>)play_targets
                   withJavaUtilList:(id<JavaUtilList>)us_acts;

- (id<JavaUtilList>)getPlayTargets;

- (id<JavaUtilList>)getPushTargets;

- (NSString *)getRoomId;

- (id<JavaUtilList>)getUsActs;

- (id<JavaUtilList>)play_targets;

- (id<JavaUtilList>)push_targets;

- (jint)reason;

- (jlong)room_id;

- (jint)schema;

- (jlong)seq;

- (NSString *)sroom_id;

- (jint)type;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (NSString *)uid;

- (id<JavaUtilList>)us_acts;

- (NSString *)ve_name;

#pragma mark Package-Private

- (jint)isValid:(NSString *)selfUid;

- (PIiRoomMessage *)retryMessage;

@end

J2OBJC_EMPTY_STATIC_INIT(PIiRoomMessage)

inline jint PIiRoomMessage_get_MSG_VALID(void);
#define PIiRoomMessage_MSG_VALID 0
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, MSG_VALID, jint)

inline jint PIiRoomMessage_get_MSG_ERR_IGNORE(void);
#define PIiRoomMessage_MSG_ERR_IGNORE 1
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, MSG_ERR_IGNORE, jint)

inline jint PIiRoomMessage_get_MSG_ERR_REPORT(void);
#define PIiRoomMessage_MSG_ERR_REPORT 2
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, MSG_ERR_REPORT, jint)

inline jint PIiRoomMessage_get_US_ACT(void);
#define PIiRoomMessage_US_ACT 50
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, US_ACT, jint)

inline jint PIiRoomMessage_get_REFRESH(void);
#define PIiRoomMessage_REFRESH 51
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, REFRESH, jint)

inline jint PIiRoomMessage_get_PEER_JOINED(void);
#define PIiRoomMessage_PEER_JOINED 54
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_JOINED, jint)

inline jint PIiRoomMessage_get_PEER_LEFT(void);
#define PIiRoomMessage_PEER_LEFT 56
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_LEFT, jint)

inline jint PIiRoomMessage_get_IROOM_DESTROYED(void);
#define PIiRoomMessage_IROOM_DESTROYED 57
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, IROOM_DESTROYED, jint)

inline jint PIiRoomMessage_get_PEER_JOINED_RETRY(void);
#define PIiRoomMessage_PEER_JOINED_RETRY 58
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_JOINED_RETRY, jint)

inline jint PIiRoomMessage_get_PEER_LEFT_RETRY(void);
#define PIiRoomMessage_PEER_LEFT_RETRY 59
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_LEFT_RETRY, jint)

inline jint PIiRoomMessage_get_IROOM_DESTROYED_RETRY(void);
#define PIiRoomMessage_IROOM_DESTROYED_RETRY 60
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, IROOM_DESTROYED_RETRY, jint)

inline jint PIiRoomMessage_get_US_ACT_RETRY(void);
#define PIiRoomMessage_US_ACT_RETRY 61
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, US_ACT_RETRY, jint)

inline jint PIiRoomMessage_get_REFRESH_RETRY(void);
#define PIiRoomMessage_REFRESH_RETRY 62
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, REFRESH_RETRY, jint)

inline jint PIiRoomMessage_get_PEER_VE_JOINED(void);
#define PIiRoomMessage_PEER_VE_JOINED 64
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_VE_JOINED, jint)

inline jint PIiRoomMessage_get_PEER_VE_LEFT(void);
#define PIiRoomMessage_PEER_VE_LEFT 66
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_VE_LEFT, jint)

inline jint PIiRoomMessage_get_PEER_VE_JOINED_RETRY(void);
#define PIiRoomMessage_PEER_VE_JOINED_RETRY 67
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_VE_JOINED_RETRY, jint)

inline jint PIiRoomMessage_get_PEER_VE_LEFT_RETRY(void);
#define PIiRoomMessage_PEER_VE_LEFT_RETRY 68
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_VE_LEFT_RETRY, jint)

inline jint PIiRoomMessage_get_PEER_PUSH_SUCCESS(void);
#define PIiRoomMessage_PEER_PUSH_SUCCESS 69
J2OBJC_STATIC_FIELD_CONSTANT(PIiRoomMessage, PEER_PUSH_SUCCESS, jint)

FOUNDATION_EXPORT void PIiRoomMessage_init(PIiRoomMessage *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PIiRoomMessage_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIiRoomMessage *PIiRoomMessage_createWithLong_withLong_withInt_withNSString_withNSString_withJavaUtilList_withJavaUtilList_withJavaUtilList_(jlong seq, jlong room_id, jint type, NSString *uid, NSString *ve_name, id<JavaUtilList> push_targets, id<JavaUtilList> play_targets, id<JavaUtilList> us_acts);

FOUNDATION_EXPORT PIiRoomMessage *PIiRoomMessage_create2WithLong_withInt_withLong_withNSString_withInt_withNSString_withNSString_withJavaUtilList_withJavaUtilList_withJavaUtilList_(jlong seq, jint reason, jlong room_id, NSString *sroom_id, jint type, NSString *uid, NSString *ve_name, id<JavaUtilList> push_targets, id<JavaUtilList> play_targets, id<JavaUtilList> us_acts);

J2OBJC_TYPE_LITERAL_HEADER(PIiRoomMessage)

@compatibility_alias ComPowerinfoPi_iroomCorePIiRoomMessage PIiRoomMessage;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_PIiRoomMessage")
