//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/PIiRoomConfig.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PIiRoomConfig")
#ifdef RESTRICT_PIiRoomConfig
#define INCLUDE_ALL_PIiRoomConfig 0
#else
#define INCLUDE_ALL_PIiRoomConfig 1
#endif
#undef RESTRICT_PIiRoomConfig

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIPIiRoomConfig_) && (INCLUDE_ALL_PIiRoomConfig || defined(INCLUDE_PIPIiRoomConfig))
#define PIPIiRoomConfig_

@class PIPIiRoomConfig_Builder;
@class PIPlayerExtraOptions;
@class PIRoomConfig;

@interface PIPIiRoomConfig : NSObject

#pragma mark Public

- (instancetype)init;

- (jint)aecMode;

- (jint)backgroundBehavior;

+ (PIPIiRoomConfig_Builder *)builder;

- (jboolean)disableAudioManager;

- (jboolean)enableDetectSpeakerAndVolume;

- (jboolean)enableVePlaySync;

- (NSString *)encUrlParamsOverride;

- (NSString *)linkUrlParamsOverride;

- (jint)onlyPlayAVAudioSessionOption;

- (jint)onlyPushAVAudioSessionOption;

- (jint)onlyPushIFrameInterval;

- (PIPlayerExtraOptions *)playerExtraOptions;

- (jboolean)playerShowBlackWhenAudioOnly;

- (jint)pushAndPlayAVAudioSessionOption;

- (jint)pushAndPlayIFrameInterval;

- (jint)pushDelayThreshold;

- (jint)pushFailTimeout;

- (NSString *)pushUrlParamsOverride;

- (jboolean)pushVideo;

- (jboolean)reportWarning;

- (jint)sdkPlayMode;

- (jint)sigMode;

- (jboolean)stopPlayOnPause;

+ (PIPIiRoomConfig *)translateRoomConfigWithPIRoomConfig:(PIRoomConfig *)roomConfig;

@end

J2OBJC_EMPTY_STATIC_INIT(PIPIiRoomConfig)

FOUNDATION_EXPORT void PIPIiRoomConfig_init(PIPIiRoomConfig *self);

FOUNDATION_EXPORT PIPIiRoomConfig_Builder *PIPIiRoomConfig_builder(void);

FOUNDATION_EXPORT PIPIiRoomConfig *PIPIiRoomConfig_translateRoomConfigWithPIRoomConfig_(PIRoomConfig *roomConfig);

J2OBJC_TYPE_LITERAL_HEADER(PIPIiRoomConfig)

@compatibility_alias ComPowerinfoPi_iroomDataPIiRoomConfig PIPIiRoomConfig;

#endif

#if !defined (PIPIiRoomConfig_Builder_) && (INCLUDE_ALL_PIiRoomConfig || defined(INCLUDE_PIPIiRoomConfig_Builder))
#define PIPIiRoomConfig_Builder_

@class PIPIiRoomConfig;
@class PIPlayerExtraOptions;

@interface PIPIiRoomConfig_Builder : NSObject

#pragma mark Public

- (instancetype)init;

- (PIPIiRoomConfig_Builder *)aecMode:(jint)aecMode;

- (PIPIiRoomConfig_Builder *)backgroundBehavior:(jint)backgroundBehavior;

- (PIPIiRoomConfig *)build;

- (PIPIiRoomConfig_Builder *)disableAudioManager:(jboolean)disableAudioManager;

- (PIPIiRoomConfig_Builder *)enableDetectSpeakerAndVolume:(jboolean)enableDetectSpeakerAndVolume;

- (PIPIiRoomConfig_Builder *)enableVePlaySync:(jboolean)enableVePlaySync;

- (PIPIiRoomConfig_Builder *)encUrlParamsOverride:(NSString *)encUrlParamsOverride;

- (PIPIiRoomConfig_Builder *)linkUrlParamsOverride:(NSString *)linkUrlParamsOverride;

- (PIPIiRoomConfig_Builder *)onlyPlayAVAudioSessionOption:(jint)onlyPlayAVAudioSessionOption;

- (PIPIiRoomConfig_Builder *)onlyPushAVAudioSessionOption:(jint)onlyPushAVAudioSessionOption;

- (PIPIiRoomConfig_Builder *)onlyPushIFrameInterval:(jint)onlyPushIFrameInterval;

- (PIPIiRoomConfig_Builder *)playerExtraOptions:(PIPlayerExtraOptions *)playerExtraOptions;

- (PIPIiRoomConfig_Builder *)playerShowBlackWhenAudioOnly:(jboolean)playerShowBlackWhenAudioOnly;

- (PIPIiRoomConfig_Builder *)pushAndPlayAVAudioSessionOption:(jint)pushAndPlayAVAudioSessionOption;

- (PIPIiRoomConfig_Builder *)pushAndPlayIFrameInterval:(jint)pushAndPlayIFrameInterval;

- (PIPIiRoomConfig_Builder *)pushDelayThreshold:(jint)pushDelayThreshold;

- (PIPIiRoomConfig_Builder *)pushFailTimeout:(jint)pushFailTimeout;

- (PIPIiRoomConfig_Builder *)pushUrlParamsOverride:(NSString *)pushUrlParamsOverride;

- (PIPIiRoomConfig_Builder *)pushVideo:(jboolean)pushVideo;

- (PIPIiRoomConfig_Builder *)reportWarning:(jboolean)reportWarning;

- (PIPIiRoomConfig_Builder *)sdkPlayMode:(jint)sdkPlayMode;

- (PIPIiRoomConfig_Builder *)sigMode:(jint)sigMode;

- (PIPIiRoomConfig_Builder *)stopPlayOnPause:(jboolean)stopPlayOnPause;

@end

J2OBJC_EMPTY_STATIC_INIT(PIPIiRoomConfig_Builder)

FOUNDATION_EXPORT void PIPIiRoomConfig_Builder_init(PIPIiRoomConfig_Builder *self);

J2OBJC_TYPE_LITERAL_HEADER(PIPIiRoomConfig_Builder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_PIiRoomConfig")
