//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/PlayerExtraOptions.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PlayerExtraOptions")
#ifdef RESTRICT_PlayerExtraOptions
#define INCLUDE_ALL_PlayerExtraOptions 0
#else
#define INCLUDE_ALL_PlayerExtraOptions 1
#endif
#undef RESTRICT_PlayerExtraOptions

#if !defined (PIPlayerExtraOptions_) && (INCLUDE_ALL_PlayerExtraOptions || defined(INCLUDE_PIPlayerExtraOptions))
#define PIPlayerExtraOptions_

@interface PIPlayerExtraOptions : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(PIPlayerExtraOptions)

FOUNDATION_EXPORT void PIPlayerExtraOptions_init(PIPlayerExtraOptions *self);

FOUNDATION_EXPORT PIPlayerExtraOptions *new_PIPlayerExtraOptions_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIPlayerExtraOptions *create_PIPlayerExtraOptions_init(void);

J2OBJC_TYPE_LITERAL_HEADER(PIPlayerExtraOptions)

@compatibility_alias ComPowerinfoPi_iroomDataPlayerExtraOptions PIPlayerExtraOptions;

#endif

#pragma pop_macro("INCLUDE_ALL_PlayerExtraOptions")
