//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/PlayerStatusInfo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PlayerStatusInfo")
#ifdef RESTRICT_PlayerStatusInfo
#define INCLUDE_ALL_PlayerStatusInfo 0
#else
#define INCLUDE_ALL_PlayerStatusInfo 1
#endif
#undef RESTRICT_PlayerStatusInfo

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (PIPlayerStatusInfo_) && (INCLUDE_ALL_PlayerStatusInfo || defined(INCLUDE_PIPlayerStatusInfo))
#define PIPlayerStatusInfo_

@class ComGoogleGsonGson;
@class ComGoogleGsonTypeAdapter;

@interface PIPlayerStatusInfo : NSObject

#pragma mark Public

- (instancetype)init;

+ (PIPlayerStatusInfo *)createWithNSString:(NSString *)uid
                              withNSString:(NSString *)v_name
                                   withInt:(jint)pzvt_delay;

- (jint)pzvt_delay;

+ (ComGoogleGsonTypeAdapter *)typeAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson;

- (NSString *)uid;

- (NSString *)ve_name;

@end

J2OBJC_EMPTY_STATIC_INIT(PIPlayerStatusInfo)

FOUNDATION_EXPORT void PIPlayerStatusInfo_init(PIPlayerStatusInfo *self);

FOUNDATION_EXPORT ComGoogleGsonTypeAdapter *PIPlayerStatusInfo_typeAdapterWithComGoogleGsonGson_(ComGoogleGsonGson *gson);

FOUNDATION_EXPORT PIPlayerStatusInfo *PIPlayerStatusInfo_createWithNSString_withNSString_withInt_(NSString *uid, NSString *v_name, jint pzvt_delay);

J2OBJC_TYPE_LITERAL_HEADER(PIPlayerStatusInfo)

@compatibility_alias ComPowerinfoPi_iroomDataPlayerStatusInfo PIPlayerStatusInfo;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_PlayerStatusInfo")
