//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/RoomConfig.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RoomConfig")
#ifdef RESTRICT_RoomConfig
#define INCLUDE_ALL_RoomConfig 0
#else
#define INCLUDE_ALL_RoomConfig 1
#endif
#undef RESTRICT_RoomConfig

#if !defined (PIRoomConfig_) && (INCLUDE_ALL_RoomConfig || defined(INCLUDE_PIRoomConfig))
#define PIRoomConfig_

@class PIPlayerExtraOptions;

@interface PIRoomConfig : NSObject {
 @public
  jint sigMode_;
  jboolean pushVideo_;
  jint sdkPlayMode_;
  jint backgroundBehavior_;
  jint pushDelayThreshold_;
  jint pushFailTimeout_;
  jint pushAndPlayIFrameInterval_;
  jint pushAndPlayAVAudioSessionOption_;
  jint onlyPushAVAudioSessionOption_;
  jint onlyPlayAVAudioSessionOption_;
  jint onlyPushIFrameInterval_;
  jboolean stopPlayOnPause_;
  jboolean disableAudioManager_;
  jboolean enableA50Support_;
  jboolean enableDetectSpeakerAndVolume_;
  jboolean reportNoneFatalRsTimeout_;
  jboolean reportWarning_;
  jint aecMode_;
  jboolean enableVePlaySync_;
  NSString *pushUrlParamsOverride_;
  NSString *linkUrlParamsOverride_;
  NSString *encUrlParamsOverride_;
  PIPlayerExtraOptions *ijkExtraOptions_;
}
@property jint sigMode;
@property jboolean pushVideo;
@property jint sdkPlayMode;
@property jint backgroundBehavior;
@property jint pushDelayThreshold;
@property jint pushFailTimeout;
@property jint pushAndPlayIFrameInterval;
@property jint pushAndPlayAVAudioSessionOption;
@property jint onlyPushAVAudioSessionOption;
@property jint onlyPlayAVAudioSessionOption;
@property jint onlyPushIFrameInterval;
@property jboolean stopPlayOnPause;
@property jboolean disableAudioManager;
@property jboolean enableA50Support;
@property jboolean enableDetectSpeakerAndVolume;
@property jboolean reportNoneFatalRsTimeout;
@property jboolean reportWarning;
@property jint aecMode;
@property (copy) NSString *pushUrlParamsOverride;
@property (copy) NSString *linkUrlParamsOverride;
@property (copy) NSString *encUrlParamsOverride;
@property PIPlayerExtraOptions *ijkExtraOptions;

#pragma mark Public

- (instancetype)initWithInt:(jint)sigMode
                withBoolean:(jboolean)pushVideo
                    withInt:(jint)sdkPlayMode
                    withInt:(jint)backgroundBehavior
                    withInt:(jint)pushDelayThreshold
                    withInt:(jint)pushFailTimeout
                    withInt:(jint)pushAndPlayIFrameInterval
                    withInt:(jint)onlyPushIFrameInterval
                    withInt:(jint)pushAndPlayAVAudioSessionOption
                    withInt:(jint)onlyPushAVAudioSessionOption
                    withInt:(jint)onlyPlayAVAudioSessionOption
                withBoolean:(jboolean)stopPlayOnPause
                withBoolean:(jboolean)disableAudioManager
                withBoolean:(jboolean)enableA50Support
                withBoolean:(jboolean)enableDetectSpeakerAndVolume
                withBoolean:(jboolean)reportNoneFatalRsTimeout
                withBoolean:(jboolean)reportWarning
                    withInt:(jint)aecMode
                withBoolean:(jboolean)enableVePlaySync
               withNSString:(NSString *)pushUrlParamsOverride
               withNSString:(NSString *)linkUrlParamsOverride
               withNSString:(NSString *)encUrlParamsOverride
   withPIPlayerExtraOptions:(PIPlayerExtraOptions *)ijkExtraOptions;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIRoomConfig)

J2OBJC_FIELD_SETTER(PIRoomConfig, pushUrlParamsOverride_, NSString *)
J2OBJC_FIELD_SETTER(PIRoomConfig, linkUrlParamsOverride_, NSString *)
J2OBJC_FIELD_SETTER(PIRoomConfig, encUrlParamsOverride_, NSString *)
J2OBJC_FIELD_SETTER(PIRoomConfig, ijkExtraOptions_, PIPlayerExtraOptions *)

FOUNDATION_EXPORT void PIRoomConfig_initWithInt_withBoolean_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withInt_withBoolean_withNSString_withNSString_withNSString_withPIPlayerExtraOptions_(PIRoomConfig *self, jint sigMode, jboolean pushVideo, jint sdkPlayMode, jint backgroundBehavior, jint pushDelayThreshold, jint pushFailTimeout, jint pushAndPlayIFrameInterval, jint onlyPushIFrameInterval, jint pushAndPlayAVAudioSessionOption, jint onlyPushAVAudioSessionOption, jint onlyPlayAVAudioSessionOption, jboolean stopPlayOnPause, jboolean disableAudioManager, jboolean enableA50Support, jboolean enableDetectSpeakerAndVolume, jboolean reportNoneFatalRsTimeout, jboolean reportWarning, jint aecMode, jboolean enableVePlaySync, NSString *pushUrlParamsOverride, NSString *linkUrlParamsOverride, NSString *encUrlParamsOverride, PIPlayerExtraOptions *ijkExtraOptions);

FOUNDATION_EXPORT PIRoomConfig *new_PIRoomConfig_initWithInt_withBoolean_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withInt_withBoolean_withNSString_withNSString_withNSString_withPIPlayerExtraOptions_(jint sigMode, jboolean pushVideo, jint sdkPlayMode, jint backgroundBehavior, jint pushDelayThreshold, jint pushFailTimeout, jint pushAndPlayIFrameInterval, jint onlyPushIFrameInterval, jint pushAndPlayAVAudioSessionOption, jint onlyPushAVAudioSessionOption, jint onlyPlayAVAudioSessionOption, jboolean stopPlayOnPause, jboolean disableAudioManager, jboolean enableA50Support, jboolean enableDetectSpeakerAndVolume, jboolean reportNoneFatalRsTimeout, jboolean reportWarning, jint aecMode, jboolean enableVePlaySync, NSString *pushUrlParamsOverride, NSString *linkUrlParamsOverride, NSString *encUrlParamsOverride, PIPlayerExtraOptions *ijkExtraOptions) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIRoomConfig *create_PIRoomConfig_initWithInt_withBoolean_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withInt_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withInt_withBoolean_withNSString_withNSString_withNSString_withPIPlayerExtraOptions_(jint sigMode, jboolean pushVideo, jint sdkPlayMode, jint backgroundBehavior, jint pushDelayThreshold, jint pushFailTimeout, jint pushAndPlayIFrameInterval, jint onlyPushIFrameInterval, jint pushAndPlayAVAudioSessionOption, jint onlyPushAVAudioSessionOption, jint onlyPlayAVAudioSessionOption, jboolean stopPlayOnPause, jboolean disableAudioManager, jboolean enableA50Support, jboolean enableDetectSpeakerAndVolume, jboolean reportNoneFatalRsTimeout, jboolean reportWarning, jint aecMode, jboolean enableVePlaySync, NSString *pushUrlParamsOverride, NSString *linkUrlParamsOverride, NSString *encUrlParamsOverride, PIPlayerExtraOptions *ijkExtraOptions);

J2OBJC_TYPE_LITERAL_HEADER(PIRoomConfig)

@compatibility_alias ComPowerinfoPi_iroomDataRoomConfig PIRoomConfig;

#endif

#pragma pop_macro("INCLUDE_ALL_RoomConfig")
