//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/utils/RsCallback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RsCallback")
#ifdef RESTRICT_RsCallback
#define INCLUDE_ALL_RsCallback 0
#else
#define INCLUDE_ALL_RsCallback 1
#endif
#undef RESTRICT_RsCallback

#if !defined (PIRsCallback_) && (INCLUDE_ALL_RsCallback || defined(INCLUDE_PIRsCallback))
#define PIRsCallback_

@protocol PIRsCallback < JavaObject >

- (void)onResponse:(id)result;

- (void)onFailure:(jint)error;

@end

J2OBJC_EMPTY_STATIC_INIT(PIRsCallback)

J2OBJC_TYPE_LITERAL_HEADER(PIRsCallback)

#define ComPowerinfoPi_iroomUtilsRsCallback PIRsCallback

#endif

#pragma pop_macro("INCLUDE_ALL_RsCallback")
