//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/data/Statistics.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Statistics")
#ifdef RESTRICT_Statistics
#define INCLUDE_ALL_Statistics 0
#else
#define INCLUDE_ALL_Statistics 1
#endif
#undef RESTRICT_Statistics

#if !defined (PIStatisticsInternal_) && (INCLUDE_ALL_Statistics || defined(INCLUDE_PIStatisticsInternal))
#define PIStatisticsInternal_

@protocol PILogger;

@interface PIStatisticsInternal : NSObject

#pragma mark Public

- (instancetype)initWithPILogger:(id<PILogger>)logger;

- (jlong)getWithEvent:(jint)event_id;

- (void)logInternal;

- (void)putWithEvent:(jint)event_id;

- (void)putWithTs:(jlong)ts
        withEvent:(jint)event_id;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(PIStatisticsInternal)

inline NSString *PIStatisticsInternal_get_TAG(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PIStatisticsInternal_TAG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PIStatisticsInternal, TAG, NSString *)

inline jint PIStatisticsInternal_get_START_JOIN(void);
#define PIStatisticsInternal_START_JOIN 0
J2OBJC_STATIC_FIELD_CONSTANT(PIStatisticsInternal, START_JOIN, jint)

inline jint PIStatisticsInternal_get_RS_REQUEST(void);
#define PIStatisticsInternal_RS_REQUEST 1
J2OBJC_STATIC_FIELD_CONSTANT(PIStatisticsInternal, RS_REQUEST, jint)

inline jint PIStatisticsInternal_get_RS_RESPONSE(void);
#define PIStatisticsInternal_RS_RESPONSE 2
J2OBJC_STATIC_FIELD_CONSTANT(PIStatisticsInternal, RS_RESPONSE, jint)

inline jint PIStatisticsInternal_get_PUSH_SUCCESS(void);
#define PIStatisticsInternal_PUSH_SUCCESS 3
J2OBJC_STATIC_FIELD_CONSTANT(PIStatisticsInternal, PUSH_SUCCESS, jint)

inline jint PIStatisticsInternal_get_FIRST_RECEIVE_SUCCESS(void);
#define PIStatisticsInternal_FIRST_RECEIVE_SUCCESS 4
J2OBJC_STATIC_FIELD_CONSTANT(PIStatisticsInternal, FIRST_RECEIVE_SUCCESS, jint)

inline jint PIStatisticsInternal_get_SIG_CONN_START(void);
#define PIStatisticsInternal_SIG_CONN_START 5
J2OBJC_STATIC_FIELD_CONSTANT(PIStatisticsInternal, SIG_CONN_START, jint)

inline jint PIStatisticsInternal_get_SIG_CONN_SUCCESS(void);
#define PIStatisticsInternal_SIG_CONN_SUCCESS 6
J2OBJC_STATIC_FIELD_CONSTANT(PIStatisticsInternal, SIG_CONN_SUCCESS, jint)

FOUNDATION_EXPORT void PIStatisticsInternal_initWithPILogger_(PIStatisticsInternal *self, id<PILogger> logger);

FOUNDATION_EXPORT PIStatisticsInternal *new_PIStatisticsInternal_initWithPILogger_(id<PILogger> logger) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PIStatisticsInternal *create_PIStatisticsInternal_initWithPILogger_(id<PILogger> logger);

J2OBJC_TYPE_LITERAL_HEADER(PIStatisticsInternal)

@compatibility_alias ComPowerinfoPi_iroomDataStatistics PIStatisticsInternal;

#endif

#pragma pop_macro("INCLUDE_ALL_Statistics")
