//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:libs/XiRoom-sources.jar!com/powerinfo/pi_iroom/window/UserWindowUpdateListenerShared.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UserWindowUpdateListenerShared")
#ifdef RESTRICT_UserWindowUpdateListenerShared
#define INCLUDE_ALL_UserWindowUpdateListenerShared 0
#else
#define INCLUDE_ALL_UserWindowUpdateListenerShared 1
#endif
#undef RESTRICT_UserWindowUpdateListenerShared

#if !defined (PIUserWindowUpdateListenerShared_) && (INCLUDE_ALL_UserWindowUpdateListenerShared || defined(INCLUDE_PIUserWindowUpdateListenerShared))
#define PIUserWindowUpdateListenerShared_

@class PIUserWindow;

@protocol PIUserWindowUpdateListenerShared < JavaObject >

- (void)onWindowAdded:(PIUserWindow *)window;

- (void)onWindowRemoved:(PIUserWindow *)window;

- (void)onWindowMoved:(PIUserWindow *)before
                After:(PIUserWindow *)after;

@end

J2OBJC_EMPTY_STATIC_INIT(PIUserWindowUpdateListenerShared)

J2OBJC_TYPE_LITERAL_HEADER(PIUserWindowUpdateListenerShared)

#define ComPowerinfoPi_iroomWindowUserWindowUpdateListenerShared PIUserWindowUpdateListenerShared

#endif

#pragma pop_macro("INCLUDE_ALL_UserWindowUpdateListenerShared")
