/* Automatically generated by version.sh, do not manually edit! */
#ifndef PIMEDIA_PIPLAYER_PIVERSION_H
#define PIMEDIA_PIPLAYER_PIVERSION_H
#define PIPLAYER_VERSION "1.9.2.0-dev-90f0d286c-20190926"
#define PS_DEMUX_VERSION "1.9.2.0-201909261700"
#endif /* PIMEDIA_PIPLAYER_PIVERSION_H */
