//
//  pscocos_macro.h
//  IJKMediaPlayer
//
//  Created by swj-macbook on 2018/11/7.
//  Copyright © 2018 PowerInfo. All rights reserved.
//

#define PSCOCOSEGINE_VERSION "1.9.2.0-20190725R00"

#define PSCOCOS_MODIFY 1

#if PSCOCOS_MODIFY
#define PSUNITY_MODIFY 0
#endif

#define PSCOCOS_DEBUG_PRINT 1

#define PSCOCOS_FLAG_KEYFRAME        1
#define PSCOCOS_FLAG_KEYEVENT        2

#define PSCOCOS_PLAYER_SOURCE         1
#define PSCOCOS_PLAYER_CLIENT         2

#define PSCOCOS_CONST_KEYWORD_LIST_SIZE 10
#define PSCOCOS_KEYWORD_MAXSIZE 30

#define PSCOCOS_PLAYER_FPS_HIGH     60
#define PSCOCOS_PLAYER_FPS_LOW         30

#define PSCOCOS_DEFAULT_BUFFERLIMIT 3600

#define PSCOCOS_DEFAULT_VERSION     -1

#define PSCOCOS_DEFAULT_SPEED         1

#define PSCOCOS_DEFAULT_SPEED_UP     1

#define PSCOCOS_DEFAULT_INTERVAL    1000
#define PSCOCOS_DEFAULT_SEEKLIMIT    4000

#define PSCOCOS_KEYLIST_MAXSIZE     256
#define PSCOCOS_KEYLENGTH_MAXSIZE     128

#define PSCOCOS_FRAME_VECTOR_MAXSIZE 120
#define PSCOCOS_SCENE_MAXSIZE 10000
#define PSCOCOS_SCENE_FULLSIZE 1000000

#define PSCOCOS_CTRLCODE_PLAYPAUSE  1
#define PSCOCOS_CTRLCODE_RESET      2
#define PSCOCOS_CTRLCODE_SPEED      3

#define PSCOCOS_PLAYER_DEFAULT_TARGET_DELAY -40
#define PSCOCOS_PLAYER_DEFAULT_SPEED_THRESHOLD 100
#define PSCOCOS_PLAYER_DEFAULT_JUMP_THRESHOLD 1000
#define PSCOCOS_PLAYER_NORMAL_STATE    0
#define PSCOCOS_PLAYER_SPEED_STATE    1
#define PSCOCOS_PLAYER_JUMP_STATE    2
#define PSCOCOS_PLAYER_TERMINATE_STATE    3
#define PSCOCOS_SAVE_STR_TO_FILE 0
#define PSCOCOS_SAVE_TIME_LOG_TO_FILE 1

#define PSCOCOS_DEFAULT_FRAMESIZE   16384
#define PSCOCOS_DEFAULT_PICTURESIZE 204800

#define PSCOCOS_MUSIC_SIZE 10000
#define PSCOCOS_MUSIC_INFO_SIZE 200


#define PSCOCOS_Log log_to_file
#define PSCOCOS_LOG_ERR     1
#define PSCOCOS_LOG_SEVERE  2

#define PSCOCOS_FREE(ptr) if(ptr!=NULL){free(ptr);ptr=NULL;}

#define PSCOCOS_REMOTE_CTRL_MAXSIZE 1000
#define PSCOCOS_REMOTE_CTRL_LENGTH_LIMIT 1000
#define PSCOCOS_REMOTE_PLAYER_LIMIT 2000
